/*
 Fuse.js v3.2.1 - Lightweight fuzzy-search (http://fusejs.io)

 Copyright (c) 2012-2017 Kirollos Risk (http://kiro.me)
 All Rights Reserved. Apache Software License 2.0

 http://www.apache.org/licenses/LICENSE-2.0
 Hammer.JS - v2.0.7 - 2016-04-22
 http://hammerjs.github.io/

 Copyright (c) 2016 Jorik Tangelder;
 Licensed under the MIT license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(p,E,z){p!=Array.prototype&&p!=Object.prototype&&(p[E]=z.value)};$jscomp.getGlobal=function(p){return"undefined"!=typeof window&&window===p?p:"undefined"!=typeof global&&null!=global?global:p};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(p){return $jscomp.SYMBOL_PREFIX+(p||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var p=$jscomp.global.Symbol.iterator;p||(p=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[p]&&$jscomp.defineProperty(Array.prototype,p,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(p){var E=0;return $jscomp.iteratorPrototype(function(){return E<p.length?{done:!1,value:p[E++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(p){$jscomp.initSymbolIterator();p={next:p};p[$jscomp.global.Symbol.iterator]=function(){return this};return p};$jscomp.makeIterator=function(p){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var E=p[Symbol.iterator];return E?E.call(p):$jscomp.arrayIterator(p)};$jscomp.arrayFromIterator=function(p){for(var E,z=[];!(E=p.next()).done;)z.push(E.value);return z};$jscomp.arrayFromIterable=function(p){return p instanceof Array?p:$jscomp.arrayFromIterator($jscomp.makeIterator(p))};
$jscomp.iteratorFromArray=function(p,E){$jscomp.initSymbolIterator();p instanceof String&&(p+="");var z=0,r={next:function(){if(z<p.length){var A=z++;return{value:E(A,p[A]),done:!1}}r.next=function(){return{done:!0,value:void 0}};return r.next()}};r[Symbol.iterator]=function(){return r};return r};
$jscomp.polyfill=function(p,E,z,r){if(E){z=$jscomp.global;p=p.split(".");for(r=0;r<p.length-1;r++){var A=p[r];A in z||(z[A]={});z=z[A]}p=p[p.length-1];r=z[p];E=E(r);E!=r&&null!=E&&$jscomp.defineProperty(z,p,{configurable:!0,writable:!0,value:E})}};$jscomp.polyfill("Array.prototype.keys",function(p){return p?p:function(){return $jscomp.iteratorFromArray(this,function(p){return p})}},"es6","es3");
$jscomp.polyfill("Array.prototype.entries",function(p){return p?p:function(){return $jscomp.iteratorFromArray(this,function(p,z){return[p,z]})}},"es6","es3");
(function(){var p="undefined"===typeof global?self:global;if("function"!==typeof p.require){var E={},z={},r={},A={}.hasOwnProperty,B=/^\.\.?(\/|$)/,n=function(a,c){var f=[];c=(B.test(c)?a+"/"+c:c).split("/");for(var v=0,g=c.length;v<g;v++)a=c[v],".."===a?f.pop():"."!==a&&""!==a&&f.push(a);return f.join("/")},w=function(a){return function(c){c=n(a.split("/").slice(0,-1).join("/"),c);return p.require(c,a)}},h=function(a){return r[a]?h(r[a]):a},m=function(a,c){return h(n(a.split("/").slice(0,-1).join("/"),
c))},x=function(a,v){null==v&&(v="/");var f=h(a);if(A.call(z,f))return z[f].exports;if(A.call(E,f))return a=E[f],v=c&&c.createHot(f),v={id:f,exports:{},hot:v},z[f]=v,a(v.exports,w(f),v),v.exports;throw Error("Cannot find module '"+a+"' from '"+v+"'");};x.alias=function(a,c){r[c]=a};var q=/\.[^.\/]+$/,d=/\/index(\.[^\/]+)?$/;x.register=x.define=function(a,c){if(a&&"object"===typeof a)for(var f in a)A.call(a,f)&&x.register(f,a[f]);else E[a]=c,delete z[a],q.test(a)&&(c=a.replace(q,""),A.call(r,c)&&r[c].replace(q,
"")!==c+"/index"||(r[c]=a)),d.test(a)&&(c=a.replace(d,""),A.call(r,c)||(r[c]=a))};x.list=function(){var a=[],c;for(c in E)A.call(E,c)&&a.push(c);return a};var c=p._hmr&&new p._hmr(m,x,E,z);x._cache=z;x.hmr=c&&c.wrap;x.brunch=!0;p.require=x}})();
(function(){var p="undefined"===typeof window?this:window,E=function(p,r,A){var B={},n=function(w,h){var m;try{return m=p(h+"/node_modules/"+w)}catch(x){if(-1===x.toString().indexOf("Cannot find module"))throw x;if(-1!==h.indexOf("node_modules"))return h=h.split("/"),m=h.lastIndexOf("node_modules"),h=h.slice(0,m).join("/"),n(w,h)}return B};return function(w){w in r&&(w=r[w]);if(w){if("."!==w[0]&&A){var h=n(w,A);if(h!==B)return h}return p(w)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(p,
r,A){r=E(r,{},"@fdaciuk/ajax");(function(){!function(B,n){"function"==typeof define&&define.amd?define("ajax",n):"object"==typeof p?p=A.exports=n():B.ajax=n()}(this,function(){function B(c,a,d,f){var v=["then","catch","always"].reduce(function(a,c){return a[c]=function(g){return a[c]=g,a},a},{}),g=new XMLHttpRequest;a=n(a,d,c);return g.open(c,a,!0),g.withCredentials=f.hasOwnProperty("withCredentials"),p(g,f.headers),g.addEventListener("readystatechange",m(v,g),!1),g.send(q(d)),v.abort=function(){return g.abort()},
v}function n(c,a,d){if("get"!==d.toLowerCase()||!a)return c;a=q(a);d=-1<c.indexOf("?")?"\x26":"?";return c+d+a}function p(c,a){a=a||{};h(a)||(a["Content-Type"]="application/x-www-form-urlencoded");Object.keys(a).forEach(function(d){a[d]&&c.setRequestHeader(d,a[d])})}function h(c){return Object.keys(c).some(function(a){return"content-type"===a.toLowerCase()})}function m(c,a){return function f(){a.readyState===a.DONE&&(a.removeEventListener("readystatechange",f,!1),c.always.apply(c,x(a)),200<=a.status&&
300>a.status?c.then.apply(c,x(a)):c["catch"].apply(c,x(a)))}}function x(c){try{var a=JSON.parse(c.responseText)}catch(v){a=c.responseText}return[a,c]}function q(c){return"[object Object]"===Object.prototype.toString.call(c)?d(c):c}function d(c){return Object.keys(c).reduce(function(a,d){return(a?a+"\x26":"")+encodeURIComponent(d)+"\x3d"+encodeURIComponent(c[d])},"")}return function(c){var a=["get","post","put","delete"];return c=c||{},c.baseUrl=c.baseUrl||"",c.method&&c.url?B(c.method,c.baseUrl+c.url,
c.data||null,c):a.reduce(function(a,f){return a[f]=function(a,g){return B(f,c.baseUrl+a,g||null,c)},a},{})}})})()});require.register("fuse.js/dist/fuse.js",function(p,r,A){r=E(r,{},"fuse.js");(function(){(function(B,n){"object"===typeof p&&"object"===typeof A?A.exports=n():"function"===typeof define&&define.amd?define("Fuse",[],n):"object"===typeof p?p.Fuse=n():B.Fuse=n()})(this,function(){return function(p){function n(h){if(B[h])return B[h].exports;var m=B[h]={i:h,l:!1,exports:{}};p[h].call(m.exports,
m,m.exports,n);m.l=!0;return m.exports}var B={};n.m=p;n.c=B;n.i=function(h){return h};n.d=function(h,m,x){n.o(h,m)||Object.defineProperty(h,m,{configurable:!1,enumerable:!0,get:x})};n.n=function(h){var m=h&&h.__esModule?function(){return h["default"]}:function(){return h};n.d(m,"a",m);return m};n.o=function(h,m){return Object.prototype.hasOwnProperty.call(h,m)};n.p="";return n(n.s=8)}([function(p,n,w){p.exports=function(h){return Array.isArray?Array.isArray(h):"[object Array]"===Object.prototype.toString.call(h)}},
function(p,n,w){var h=function(){function d(c,a){for(var d=0;d<a.length;d++){var f=a[d];f.enumerable=f.enumerable||!1;f.configurable=!0;"value"in f&&(f.writable=!0);Object.defineProperty(c,f.key,f)}}return function(c,a,v){a&&d(c.prototype,a);v&&d(c,v);return c}}(),m=w(5),x=w(7),q=w(4);n=function(){function d(c,a){var v=a.location;v=void 0===v?0:v;var f=a.distance;f=void 0===f?100:f;var m=a.threshold;m=void 0===m?.6:m;var g=a.maxPatternLength;g=void 0===g?32:g;var l=a.isCaseSensitive;l=void 0===l?
!1:l;var u=a.tokenSeparator;u=void 0===u?/ +/g:u;var e=a.findAllMatches;e=void 0===e?!1:e;a=a.minMatchCharLength;a=void 0===a?1:a;if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");this.options={location:v,distance:f,threshold:m,maxPatternLength:g,isCaseSensitive:l,tokenSeparator:u,findAllMatches:e,minMatchCharLength:a};this.pattern=this.options.isCaseSensitive?c:c.toLowerCase();this.pattern.length<=g&&(this.patternAlphabet=q(this.pattern))}h(d,[{key:"search",value:function(c){this.options.isCaseSensitive||
(c=c.toLowerCase());if(this.pattern===c)return{isMatch:!0,score:0,matchedIndices:[[0,c.length-1]]};var a=this.options,d=a.tokenSeparator;if(this.pattern.length>a.maxPatternLength)return m(c,this.pattern,d);a=this.options;return x(c,this.pattern,this.patternAlphabet,{location:a.location,distance:a.distance,threshold:a.threshold,findAllMatches:a.findAllMatches,minMatchCharLength:a.minMatchCharLength})}}]);return d}();p.exports=n},function(p,n,w){var h=w(0),m=function q(d,c,a){if(c){var v=c.indexOf("."),
f=c,m=null;-1!==v&&(f=c.slice(0,v),m=c.slice(v+1));d=d[f];if(null!==d&&void 0!==d)if(m||"string"!==typeof d&&"number"!==typeof d)if(h(d))for(c=0,v=d.length;c<v;c+=1)q(d[c],m,a);else m&&q(d,m,a);else a.push(d.toString())}else a.push(d);return a};p.exports=function(h,d){return m(h,d,[])}},function(p,n,w){p.exports=function(){for(var h=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],m=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,n=[],q=-1,d,c=0,a=h.length;c<a;c+=1)(d=h[c])&&-1===
q?q=c:d||-1===q||(d=c-1,d-q+1>=m&&n.push([q,d]),q=-1);h[c-1]&&c-q>=m&&n.push([q,c-1]);return n}},function(p,n,w){p.exports=function(h){for(var m={},n=h.length,q=0;q<n;q+=1)m[h.charAt(q)]=0;for(q=0;q<n;q+=1)m[h.charAt(q)]|=1<<n-q-1;return m}},function(p,n,w){var h=/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g;p.exports=function(m,n){var q=2<arguments.length&&void 0!==arguments[2]?arguments[2]:/ +/g;q=new RegExp(n.replace(h,"\\$\x26").replace(q,"|"));q=m.match(q);var d=!!q,c=[];if(d)for(var a=0,v=q.length;a<
v;a+=1){var f=q[a];c.push([m.indexOf(f),f.length-1])}return{score:d?.5:1,isMatch:d,matchedIndices:c}}},function(p,n,w){p.exports=function(h,m){var n=m.errors,q=m.currentLocation,d=m.expectedLocation;m=m.distance;m=void 0===m?100:m;h=(void 0===n?0:n)/h.length;q=Math.abs((void 0===d?0:d)-(void 0===q?0:q));return m?h+q/m:q?1:h}},function(p,n,w){var h=w(6),m=w(3);p.exports=function(n,q,d,c){var a=c.location,v=c.distance;v=void 0===v?100:v;var f=c.threshold,y=c.findAllMatches;y=void 0===y?!1:y;c=c.minMatchCharLength;
c=void 0===c?1:c;a=void 0===a?0:a;var g=n.length;f=void 0===f?.6:f;for(var l=n.indexOf(q,a),u=q.length,e=[],b=0;b<g;b+=1)e[b]=0;-1!==l&&(l=h(q,{errors:0,currentLocation:l,expectedLocation:a,distance:v}),f=Math.min(l,f),l=n.lastIndexOf(q,a+u),-1!==l&&(l=h(q,{errors:0,currentLocation:l,expectedLocation:a,distance:v}),f=Math.min(l,f)));l=-1;b=[];for(var k=1,H=u+g,C=1<<u-1,I=0;I<u;I+=1){for(var p=0,G=H;p<G;)h(q,{errors:I,currentLocation:a+G,expectedLocation:a,distance:v})<=f?p=G:H=G,G=Math.floor((H-p)/
2+p);H=G;p=Math.max(1,a-G+1);var F=y?g:Math.min(a+G,g)+u;G=Array(F+2);for(G[F+1]=(1<<I)-1;F>=p;--F){var K=F-1,P=d[n.charAt(K)];P&&(e[K]=1);G[F]=(G[F+1]<<1|1)&P;0!==I&&(G[F]=G[F]|(b[F+1]|b[F])<<1|1|b[F+1]);if(G[F]&C&&(k=h(q,{errors:I,currentLocation:K,expectedLocation:a,distance:v}),k<=f)){f=k;l=K;if(l<=a)break;p=Math.max(1,2*a-l)}}if(h(q,{errors:I+1,currentLocation:a,expectedLocation:a,distance:v})>f)break;b=G}return{isMatch:0<=l,score:0===k?.001:k,matchedIndices:m(e,c)}}},function(p,n,w){var h=function(){function d(c,
a){for(var d=0;d<a.length;d++){var f=a[d];f.enumerable=f.enumerable||!1;f.configurable=!0;"value"in f&&(f.writable=!0);Object.defineProperty(c,f.key,f)}}return function(c,a,v){a&&d(c.prototype,a);v&&d(c,v);return c}}(),m=w(1),x=w(2),q=w(0);n=function(){function d(c,a){var v=a.location;v=void 0===v?0:v;var f=a.distance;f=void 0===f?100:f;var m=a.threshold;m=void 0===m?.6:m;var g=a.maxPatternLength;g=void 0===g?32:g;var l=a.caseSensitive;l=void 0===l?!1:l;var u=a.tokenSeparator;u=void 0===u?/ +/g:u;
var e=a.findAllMatches;e=void 0===e?!1:e;var b=a.minMatchCharLength;b=void 0===b?1:b;var k=a.id;k=void 0===k?null:k;var H=a.keys;H=void 0===H?[]:H;var C=a.shouldSort;C=void 0===C?!0:C;var I=a.getFn;I=void 0===I?x:I;var h=a.sortFn;h=void 0===h?function(b,a){return b.score-a.score}:h;var G=a.tokenize;G=void 0===G?!1:G;var F=a.matchAllTokens;F=void 0===F?!1:F;var n=a.includeMatches;n=void 0===n?!1:n;var p=a.includeScore;p=void 0===p?!1:p;a=a.verbose;a=void 0===a?!1:a;if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");
this.options={location:v,distance:f,threshold:m,maxPatternLength:g,isCaseSensitive:l,tokenSeparator:u,findAllMatches:e,minMatchCharLength:b,id:k,keys:H,includeMatches:n,includeScore:p,shouldSort:C,getFn:I,sortFn:h,verbose:a,tokenize:G,matchAllTokens:F};this.setCollection(c)}h(d,[{key:"setCollection",value:function(c){return this.list=c}},{key:"search",value:function(c){this._log('---------\nSearch pattern: "'+c+'"');c=this._prepareSearchers(c);c=this._search(c.tokenSearchers,c.fullSearcher);var a=
c.results;this._computeScore(c.weights,a);this.options.shouldSort&&this._sort(a);return this._format(a)}},{key:"_prepareSearchers",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",a=[];if(this.options.tokenize)for(var d=c.split(this.options.tokenSeparator),f=0,h=d.length;f<h;f+=1)a.push(new m(d[f],this.options));c=new m(c,this.options);return{tokenSearchers:a,fullSearcher:c}}},{key:"_search",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:
[],a=arguments[1],d=this.list,f={},m=[];if("string"===typeof d[0]){for(var g=0,l=d.length;g<l;g+=1)this._analyze({key:"",value:d[g],record:g,index:g},{resultMap:f,results:m,tokenSearchers:c,fullSearcher:a});return{weights:null,results:m}}g={};l=0;for(var u=d.length;l<u;l+=1)for(var e=d[l],b=0,k=this.options.keys.length;b<k;b+=1){var H=this.options.keys[b];if("string"!==typeof H){g[H.name]={weight:1-H.weight||1};if(0>=H.weight||1<H.weight)throw Error("Key weight has to be \x3e 0 and \x3c\x3d 1");H=
H.name}else g[H]={weight:1};this._analyze({key:H,value:this.options.getFn(e,H),record:e,index:l},{resultMap:f,results:m,tokenSearchers:c,fullSearcher:a})}return{weights:g,results:m}}},{key:"_analyze",value:function(c,a){var d=c.key,f=c.arrayIndex,m=void 0===f?-1:f;f=c.value;var g=c.record;c=c.index;var l=a.tokenSearchers;l=void 0===l?[]:l;var u=a.fullSearcher,e=void 0===u?[]:u;u=a.resultMap;u=void 0===u?{}:u;a=a.results;a=void 0===a?[]:a;if(void 0!==f&&null!==f){var b=!1,k=-1,H=0;if("string"===typeof f){this._log("\nKey: "+
(""===d?"-":d));e=e.search(f);this._log('Full text: "'+f+'", score: '+e.score);if(this.options.tokenize){k=f.split(this.options.tokenSeparator);for(var C=[],I=0;I<l.length;I+=1){var h=l[I];this._log('\nPattern: "'+h.pattern+'"');for(var G=!1,F=0;F<k.length;F+=1){var n=k[F],p=h.search(n),D={};p.isMatch?(D[n]=p.score,G=b=!0,C.push(p.score)):(D[n]=1,this.options.matchAllTokens||C.push(1));this._log('Token: "'+n+'", score: '+D[n])}G&&(H+=1)}k=C[0];I=C.length;for(h=1;h<I;h+=1)k+=C[h];k/=I;this._log("Token score average:",
k)}C=e.score;-1<k&&(C=(C+k)/2);this._log("Score average:",C);l=this.options.tokenize&&this.options.matchAllTokens?H>=l.length:!0;this._log("\nCheck Matches: "+l);(b||e.isMatch)&&l&&((l=u[c])?l.output.push({key:d,arrayIndex:m,value:f,score:C,matchedIndices:e.matchedIndices}):(u[c]={item:g,output:[{key:d,arrayIndex:m,value:f,score:C,matchedIndices:e.matchedIndices}]},a.push(u[c])))}else if(q(f))for(m=0,b=f.length;m<b;m+=1)this._analyze({key:d,arrayIndex:m,value:f[m],record:g,index:c},{resultMap:u,results:a,
tokenSearchers:l,fullSearcher:e})}}},{key:"_computeScore",value:function(c,a){this._log("\n\nComputing score:\n");for(var d=0,f=a.length;d<f;d+=1){for(var m=a[d].output,g=m.length,l=1,u=1,e=0;e<g;e+=1){var b=c?c[m[e].key].weight:1,k=(1===b?m[e].score:m[e].score||.001)*b;1!==b?u=Math.min(u,k):(m[e].nScore=k,l*=k)}a[d].score=1===u?l:u;this._log(a[d])}}},{key:"_sort",value:function(c){this._log("\n\nSorting....");c.sort(this.options.sortFn)}},{key:"_format",value:function(c){var a=[];this.options.verbose&&
this._log("\n\nOutput:\n\n",JSON.stringify(c));var d=[];this.options.includeMatches&&d.push(function(b,a){b=b.output;a.matches=[];for(var c=0,k=b.length;c<k;c+=1){var g=b[c];if(0!==g.matchedIndices.length){var e={indices:g.matchedIndices,value:g.value};g.key&&(e.key=g.key);g.hasOwnProperty("arrayIndex")&&-1<g.arrayIndex&&(e.arrayIndex=g.arrayIndex);a.matches.push(e)}}});this.options.includeScore&&d.push(function(b,a){a.score=b.score});for(var f=0,m=c.length;f<m;f+=1){var g=c[f];this.options.id&&(g.item=
this.options.getFn(g.item,this.options.id)[0]);if(d.length){for(var l={item:g.item},u=0,e=d.length;u<e;u+=1)d[u](g,l);a.push(l)}else a.push(g.item)}return a}},{key:"_log",value:function(){if(this.options.verbose){var c;(c=console).log.apply(c,arguments)}}}]);return d}();p.exports=n}])})})()});require.register("hammerjs/hammer.js",function(p,r,A){r=E(r,{},"hammerjs");(function(){(function(p,n,w,h){function m(b,c,g){return setTimeout(a(b,g),c)}function x(b,a,c){return Array.isArray(b)?(q(b,c[a],c),
!0):!1}function q(b,a,c){var t;if(b)if(b.forEach)b.forEach(a,c);else if(b.length!==h)for(t=0;t<b.length;)a.call(c,b[t],t,b),t++;else for(t in b)b.hasOwnProperty(t)&&a.call(c,b[t],t,b)}function d(b,a,c){var t="DEPRECATED METHOD: "+a+"\n"+c+" AT \n";return function(){var a=Error("get-stack-trace");a=a&&a.stack?a.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@"):"Unknown Stack Trace";var c=p.console&&(p.console.warn||p.console.log);c&&
c.call(p.console,t,a);return b.apply(this,arguments)}}function c(b,a,c){a=a.prototype;var t=b.prototype=Object.create(a);t.constructor=b;t._super=a;c&&O(t,c)}function a(b,a){return function(){return b.apply(a,arguments)}}function v(b,a){return"function"==typeof b?b.apply(a?a[0]||h:h,a):b}function f(b,a,c){q(l(a),function(t){b.addEventListener(t,c,!1)})}function y(b,a,c){q(l(a),function(t){b.removeEventListener(t,c,!1)})}function g(b,a){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}function l(b){return b.trim().split(/\s+/g)}
function u(b,a,c){if(b.indexOf&&!c)return b.indexOf(a);for(var t=0;t<b.length;){if(c&&b[t][c]==a||!c&&b[t]===a)return t;t++}return-1}function e(b){return Array.prototype.slice.call(b,0)}function b(b,a,c){for(var t=[],g=[],k=0;k<b.length;){var e=a?b[k][a]:b[k];0>u(g,e)&&t.push(b[k]);g[k]=e;k++}c&&(t=a?t.sort(function(b,t){return b[a]>t[a]}):t.sort());return t}function k(b,a){for(var t,c=a[0].toUpperCase()+a.slice(1),k=0;k<ha.length;){t=(t=ha[k])?t+c:a;if(t in b)return t;k++}return h}function H(b){b=
b.ownerDocument||b;return b.defaultView||b.parentWindow||p}function C(b,a){var t=this;this.manager=b;this.callback=a;this.element=b.element;this.target=b.options.inputTarget;this.domHandler=function(a){v(b.options.enable,[b])&&t.handler(a)};this.init()}function I(b){var a=b.options.inputClass;return new (a?a:ta?X:ua?z:ia?Y:r)(b,sa)}function sa(b,a,c){var t=c.pointers.length,k=c.changedPointers.length;var e=a&1&&0===t-k;c.isFirst=!!e;c.isFinal=!!(a&12&&0===t-k);e&&(b.session={});c.eventType=a;a=b.session;
t=c.pointers;k=t.length;a.firstInput||(a.firstInput=G(c));1<k&&!a.firstMultiple?a.firstMultiple=G(c):1===k&&(a.firstMultiple=!1);e=a.firstInput;var l=(k=a.firstMultiple)?k.center:e.center;var C=c.center=F(t);c.timeStamp=Z();c.deltaTime=c.timeStamp-e.timeStamp;c.angle=D(l,C);c.distance=P(l,C);e=c.center;l=a.offsetDelta||{};C=a.prevDelta||{};var d=a.prevInput||{};if(1===c.eventType||4===d.eventType)C=a.prevDelta={x:d.deltaX||0,y:d.deltaY||0},l=a.offsetDelta={x:e.x,y:e.y};c.deltaX=C.x+(e.x-l.x);c.deltaY=
C.y+(e.y-l.y);c.offsetDirection=K(c.deltaX,c.deltaY);l=c.deltaTime;e=c.deltaX/l||0;l=c.deltaY/l||0;c.overallVelocityX=e;c.overallVelocityY=l;c.overallVelocity=Q(e)>Q(l)?e:l;k?(e=k.pointers,e=P(t[0],t[1],S)/P(e[0],e[1],S)):e=1;c.scale=e;k?(k=k.pointers,t=D(t[1],t[0],S)+D(k[1],k[0],S)):t=0;c.rotation=t;c.maxPointers=a.prevInput?c.pointers.length>a.prevInput.maxPointers?c.pointers.length:a.prevInput.maxPointers:c.pointers.length;l=a.lastInterval||c;t=c.timeStamp-l.timeStamp;8!=c.eventType&&(25<t||l.velocity===
h)?(e=c.deltaX-l.deltaX,l=c.deltaY-l.deltaY,C=e/t||0,d=l/t||0,t=C,k=d,C=Q(C)>Q(d)?C:d,e=K(e,l),a.lastInterval=c):(C=l.velocity,t=l.velocityX,k=l.velocityY,e=l.direction);c.velocity=C;c.velocityX=t;c.velocityY=k;c.direction=e;a=b.element;g(c.srcEvent.target,a)&&(a=c.srcEvent.target);c.target=a;b.emit("hammer.input",c);b.recognize(c);b.session.prevInput=c}function G(b){for(var a=[],c=0;c<b.pointers.length;)a[c]={clientX:R(b.pointers[c].clientX),clientY:R(b.pointers[c].clientY)},c++;return{timeStamp:Z(),
pointers:a,center:F(a),deltaX:b.deltaX,deltaY:b.deltaY}}function F(b){var a=b.length;if(1===a)return{x:R(b[0].clientX),y:R(b[0].clientY)};for(var c=0,t=0,k=0;k<a;)c+=b[k].clientX,t+=b[k].clientY,k++;return{x:R(c/a),y:R(t/a)}}function K(b,a){return b===a?1:Q(b)>=Q(a)?0>b?2:4:0>a?8:16}function P(b,a,c){c||(c=ja);var t=a[c[0]]-b[c[0]];b=a[c[1]]-b[c[1]];return Math.sqrt(t*t+b*b)}function D(b,a,c){c||(c=ja);return 180*Math.atan2(a[c[1]]-b[c[1]],a[c[0]]-b[c[0]])/Math.PI}function r(){this.evEl=va;this.evWin=
wa;this.pressed=!1;C.apply(this,arguments)}function X(){this.evEl=ka;this.evWin=la;C.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function B(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;C.apply(this,arguments)}function z(){this.evTarget=xa;this.targetIds={};C.apply(this,arguments)}function E(a,c){var t=e(a.touches),k=this.targetIds;if(c&3&&1===t.length)return k[t[0].identifier]=!0,[t,t];a=e(a.changedTouches);var l=[],
C=this.target;var d=t.filter(function(b){return g(b.target,C)});if(1===c)for(t=0;t<d.length;)k[d[t].identifier]=!0,t++;for(t=0;t<a.length;)k[a[t].identifier]&&l.push(a[t]),c&12&&delete k[a[t].identifier],t++;if(l.length)return[b(d.concat(l),"identifier",!0),l]}function Y(){C.apply(this,arguments);var b=a(this.handler,this);this.touch=new z(this.manager,b);this.mouse=new r(this.manager,b);this.primaryTouch=null;this.lastTouches=[]}function J(b){b=b.changedPointers[0];if(b.identifier===this.primaryTouch){var a=
{x:b.clientX,y:b.clientY};this.lastTouches.push(a);var c=this.lastTouches;setTimeout(function(){var b=c.indexOf(a);-1<b&&c.splice(b,1)},2500)}}function aa(b,a){this.manager=b;this.set(a)}function ya(b){if(-1<b.indexOf("none"))return"none";var a=-1<b.indexOf("pan-x"),c=-1<b.indexOf("pan-y");return a&&c?"none":a||c?a?"pan-x":"pan-y":-1<b.indexOf("manipulation")?"manipulation":"auto"}function M(b){this.options=O({},this.defaults,b||{});this.id=za++;this.manager=null;b=this.options.enable;this.options.enable=
b===h?!0:b;this.state=1;this.simultaneous={};this.requireFail=[]}function ma(b){return b&16?"cancel":b&8?"end":b&4?"move":b&2?"start":""}function na(b){return 16==b?"down":8==b?"up":2==b?"left":4==b?"right":""}function T(b,a){return(a=a.manager)?a.get(b):b}function L(){M.apply(this,arguments)}function U(){L.apply(this,arguments);this.pY=this.pX=null}function ba(){L.apply(this,arguments)}function ca(){M.apply(this,arguments);this._input=this._timer=null}function da(){L.apply(this,arguments)}function ea(){L.apply(this,
arguments)}function V(){M.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function N(b,a){a=a||{};var c=a.recognizers;a.recognizers=c===h?N.defaults.preset:c;return new fa(b,a)}function fa(b,a){this.options=O({},N.defaults,a||{});this.options.inputTarget=this.options.inputTarget||b;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=b;this.input=I(this);this.touchAction=new aa(this,this.options.touchAction);oa(this,!0);q(this.options.recognizers,
function(b){var a=this.add(new b[0](b[1]));b[2]&&a.recognizeWith(b[2]);b[3]&&a.requireFailure(b[3])},this)}function oa(b,a){var c=b.element;if(c.style){var t;q(b.options.cssProps,function(g,e){t=k(c.style,e);a?(b.oldCssProps[t]=c.style[t],c.style[t]=g):c.style[t]=b.oldCssProps[t]||""});a||(b.oldCssProps={})}}function Aa(b,a){var c=n.createEvent("Event");c.initEvent(b,!0,!0);c.gesture=a;a.target.dispatchEvent(c)}var ha=" webkit Moz MS ms o".split(" "),Ba=n.createElement("div"),R=Math.round,Q=Math.abs,
Z=Date.now;var O="function"!==typeof Object.assign?function(b){if(b===h||null===b)throw new TypeError("Cannot convert undefined or null to object");for(var a=Object(b),c=1;c<arguments.length;c++){var k=arguments[c];if(k!==h&&null!==k)for(var t in k)k.hasOwnProperty(t)&&(a[t]=k[t])}return a}:Object.assign;var pa=d(function(b,a,c){for(var k=Object.keys(a),t=0;t<k.length;){if(!c||c&&b[k[t]]===h)b[k[t]]=a[k[t]];t++}return b},"extend","Use `assign`."),Ca=d(function(b,a){return pa(b,a,!0)},"merge","Use `assign`."),
za=1,Da=/mobile|tablet|ip(ad|hone|od)|android/i,ia="ontouchstart"in p,ta=k(p,"PointerEvent")!==h,ua=ia&&Da.test(navigator.userAgent),ja=["x","y"],S=["clientX","clientY"];C.prototype={handler:function(){},init:function(){this.evEl&&f(this.element,this.evEl,this.domHandler);this.evTarget&&f(this.target,this.evTarget,this.domHandler);this.evWin&&f(H(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&y(this.element,this.evEl,this.domHandler);this.evTarget&&y(this.target,this.evTarget,
this.domHandler);this.evWin&&y(H(this.element),this.evWin,this.domHandler)}};var Ea={mousedown:1,mousemove:2,mouseup:4},va="mousedown",wa="mousemove mouseup";c(r,C,{handler:function(b){var a=Ea[b.type];a&1&&0===b.button&&(this.pressed=!0);a&2&&1!==b.which&&(a=4);this.pressed&&(a&4&&(this.pressed=!1),this.callback(this.manager,a,{pointers:[b],changedPointers:[b],pointerType:"mouse",srcEvent:b}))}});var Fa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ga={2:"touch",3:"pen",
4:"mouse",5:"kinect"},ka="pointerdown",la="pointermove pointerup pointercancel";p.MSPointerEvent&&!p.PointerEvent&&(ka="MSPointerDown",la="MSPointerMove MSPointerUp MSPointerCancel");c(X,C,{handler:function(b){var a=this.store,c=!1,k=b.type.toLowerCase().replace("ms","");k=Fa[k];var g=Ga[b.pointerType]||b.pointerType,e="touch"==g,t=u(a,b.pointerId,"pointerId");k&1&&(0===b.button||e)?0>t&&(a.push(b),t=a.length-1):k&12&&(c=!0);0>t||(a[t]=b,this.callback(this.manager,k,{pointers:a,changedPointers:[b],
pointerType:g,srcEvent:b}),c&&a.splice(t,1))}});var Ha={touchstart:1,touchmove:2,touchend:4,touchcancel:8};c(B,C,{handler:function(a){var c=Ha[a.type];1===c&&(this.started=!0);if(this.started){var k=e(a.touches);var g=e(a.changedTouches);c&12&&(k=b(k.concat(g),"identifier",!0));k=[k,g];c&12&&0===k[0].length-k[1].length&&(this.started=!1);this.callback(this.manager,c,{pointers:k[0],changedPointers:k[1],pointerType:"touch",srcEvent:a})}}});var Ia={touchstart:1,touchmove:2,touchend:4,touchcancel:8},
xa="touchstart touchmove touchend touchcancel";c(z,C,{handler:function(b){var a=Ia[b.type],c=E.call(this,b,a);c&&this.callback(this.manager,a,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:b})}});c(Y,C,{handler:function(b,a,c){var k="mouse"==c.pointerType;if(!(k&&c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents)){if("touch"==c.pointerType)a&1?(this.primaryTouch=c.changedPointers[0].identifier,J.call(this,c)):a&12&&J.call(this,c);else{if(k)a:{k=c.srcEvent.clientX;for(var g=
c.srcEvent.clientY,e=0;e<this.lastTouches.length;e++){var t=this.lastTouches[e],l=Math.abs(g-t.y);if(25>=Math.abs(k-t.x)&&25>=l){k=!0;break a}}k=!1}if(k)return}this.callback(b,a,c)}},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var qa=k(Ba.style,"touchAction"),ra=qa!==h,W=function(){if(!ra)return!1;var b={},a=p.CSS&&p.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(c){b[c]=a?p.CSS.supports("touch-action",c):!0});return b}();aa.prototype=
{set:function(b){"compute"==b&&(b=this.compute());ra&&this.manager.element.style&&W[b]&&(this.manager.element.style[qa]=b);this.actions=b.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var b=[];q(this.manager.recognizers,function(a){v(a.options.enable,[a])&&(b=b.concat(a.getTouchAction()))});return ya(b.join(" "))},preventDefaults:function(b){var a=b.srcEvent,c=b.offsetDirection;if(this.manager.session.prevented)a.preventDefault();else{var k=
this.actions,g=-1<k.indexOf("none")&&!W.none,e=-1<k.indexOf("pan-y")&&!W["pan-y"];k=-1<k.indexOf("pan-x")&&!W["pan-x"];if(g){var l=2>b.distance,t=250>b.deltaTime;if(1===b.pointers.length&&l&&t)return}if(!k||!e)if(g||e&&c&6||k&&c&24)return this.preventSrc(a)}},preventSrc:function(b){this.manager.session.prevented=!0;b.preventDefault()}};M.prototype={defaults:{},set:function(b){O(this.options,b);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(b){if(x(b,"recognizeWith",
this))return this;var a=this.simultaneous;b=T(b,this);a[b.id]||(a[b.id]=b,b.recognizeWith(this));return this},dropRecognizeWith:function(b){if(x(b,"dropRecognizeWith",this))return this;b=T(b,this);delete this.simultaneous[b.id];return this},requireFailure:function(b){if(x(b,"requireFailure",this))return this;var a=this.requireFail;b=T(b,this);-1===u(a,b)&&(a.push(b),b.requireFailure(this));return this},dropRequireFailure:function(b){if(x(b,"dropRequireFailure",this))return this;b=T(b,this);b=u(this.requireFail,
b);-1<b&&this.requireFail.splice(b,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(b){return!!this.simultaneous[b.id]},emit:function(b){function a(a){c.manager.emit(a,b)}var c=this,k=this.state;8>k&&a(c.options.event+ma(k));a(c.options.event);b.additionalEvent&&a(b.additionalEvent);8<=k&&a(c.options.event+ma(k))},tryEmit:function(b){if(this.canEmit())return this.emit(b);this.state=32},canEmit:function(){for(var b=0;b<this.requireFail.length;){if(!(this.requireFail[b].state&
33))return!1;b++}return!0},recognize:function(b){b=O({},b);v(this.options.enable,[this,b])?(this.state&56&&(this.state=1),this.state=this.process(b),this.state&30&&this.tryEmit(b)):(this.reset(),this.state=32)},process:function(b){},getTouchAction:function(){},reset:function(){}};c(L,M,{defaults:{pointers:1},attrTest:function(b){var a=this.options.pointers;return 0===a||b.pointers.length===a},process:function(b){var a=this.state,c=b.eventType,k=a&6;b=this.attrTest(b);return k&&(c&8||!b)?a|16:k||b?
c&4?a|8:a&2?a|4:2:32}});c(U,L,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var b=this.options.direction,a=[];b&6&&a.push("pan-y");b&24&&a.push("pan-x");return a},directionTest:function(b){var a=this.options,c=!0,k=b.distance,g=b.direction,e=b.deltaX,l=b.deltaY;g&a.direction||(a.direction&6?(g=0===e?1:0>e?2:4,c=e!=this.pX,k=Math.abs(b.deltaX)):(g=0===l?1:0>l?8:16,c=l!=this.pY,k=Math.abs(b.deltaY)));b.direction=g;return c&&k>a.threshold&&g&a.direction},attrTest:function(b){return L.prototype.attrTest.call(this,
b)&&(this.state&2||!(this.state&2)&&this.directionTest(b))},emit:function(b){this.pX=b.deltaX;this.pY=b.deltaY;var a=na(b.direction);a&&(b.additionalEvent=this.options.event+a);this._super.emit.call(this,b)}});c(ba,L,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.scale-1)>this.options.threshold||this.state&2)},emit:function(b){1!==b.scale&&(b.additionalEvent=this.options.event+(1>
b.scale?"in":"out"));this._super.emit.call(this,b)}});c(ca,M,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},process:function(b){var a=this.options,c=b.pointers.length===a.pointers,k=b.distance<a.threshold,g=b.deltaTime>a.time;this._input=b;if(!k||!c||b.eventType&12&&!g)this.reset();else if(b.eventType&1)this.reset(),this._timer=m(function(){this.state=8;this.tryEmit()},a.time,this);else if(b.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},
emit:function(b){8===this.state&&(b&&b.eventType&4?this.manager.emit(this.options.event+"up",b):(this._input.timeStamp=Z(),this.manager.emit(this.options.event,this._input)))}});c(da,L,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.rotation)>this.options.threshold||this.state&2)}});c(ea,L,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return U.prototype.getTouchAction.call(this)},
attrTest:function(b){var a=this.options.direction;if(a&30)var c=b.overallVelocity;else a&6?c=b.overallVelocityX:a&24&&(c=b.overallVelocityY);return this._super.attrTest.call(this,b)&&a&b.offsetDirection&&b.distance>this.options.threshold&&b.maxPointers==this.options.pointers&&Q(c)>this.options.velocity&&b.eventType&4},emit:function(b){var a=na(b.offsetDirection);a&&this.manager.emit(this.options.event+a,b);this.manager.emit(this.options.event,b)}});c(V,M,{defaults:{event:"tap",pointers:1,taps:1,interval:300,
time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(b){var a=this.options,c=b.pointers.length===a.pointers,k=b.distance<a.threshold,g=b.deltaTime<a.time;this.reset();if(b.eventType&1&&0===this.count)return this.failTimeout();if(k&&g&&c){if(4!=b.eventType)return this.failTimeout();c=this.pTime?b.timeStamp-this.pTime<a.interval:!0;k=!this.pCenter||P(this.pCenter,b.center)<a.posThreshold;this.pTime=b.timeStamp;this.pCenter=b.center;this.count=k&&c?
this.count+1:1;this._input=b;if(0===this.count%a.taps)return this.hasRequireFailures()?(this._timer=m(function(){this.state=8;this.tryEmit()},a.interval,this),2):8}return 32},failTimeout:function(){this._timer=m(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});N.VERSION="2.0.7";N.defaults={domEvents:!1,touchAction:"compute",
enable:!0,inputTarget:null,inputClass:null,preset:[[da,{enable:!1}],[ba,{enable:!1},["rotate"]],[ea,{direction:6}],[U,{direction:6},["swipe"]],[V],[V,{event:"doubletap",taps:2},["tap"]],[ca]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};fa.prototype={set:function(b){O(this.options,b);b.touchAction&&this.touchAction.update();b.inputTarget&&(this.input.destroy(),this.input.target=b.inputTarget,this.input.init());
return this},stop:function(b){this.session.stopped=b?2:1},recognize:function(b){var a=this.session;if(!a.stopped){this.touchAction.preventDefaults(b);var c=this.recognizers,k=a.curRecognizer;if(!k||k&&k.state&8)k=a.curRecognizer=null;for(var g=0;g<c.length;){var e=c[g];2===a.stopped||k&&e!=k&&!e.canRecognizeWith(k)?e.reset():e.recognize(b);!k&&e.state&14&&(k=a.curRecognizer=e);g++}}},get:function(b){if(b instanceof M)return b;for(var a=this.recognizers,c=0;c<a.length;c++)if(a[c].options.event==b)return a[c];
return null},add:function(b){if(x(b,"add",this))return this;var a=this.get(b.options.event);a&&this.remove(a);this.recognizers.push(b);b.manager=this;this.touchAction.update();return b},remove:function(b){if(x(b,"remove",this))return this;if(b=this.get(b)){var a=this.recognizers;b=u(a,b);-1!==b&&(a.splice(b,1),this.touchAction.update())}return this},on:function(b,a){if(b!==h&&a!==h){var c=this.handlers;q(l(b),function(b){c[b]=c[b]||[];c[b].push(a)});return this}},off:function(b,a){if(b!==h){var c=
this.handlers;q(l(b),function(b){a?c[b]&&c[b].splice(u(c[b],a),1):delete c[b]});return this}},emit:function(b,a){this.options.domEvents&&Aa(b,a);var c=this.handlers[b]&&this.handlers[b].slice();if(c&&c.length)for(a.type=b,a.preventDefault=function(){a.srcEvent.preventDefault()},b=0;b<c.length;)c[b](a),b++},destroy:function(){this.element&&oa(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};O(N,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,
STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:fa,Input:C,TouchAction:aa,TouchInput:z,MouseInput:r,PointerEventInput:X,TouchMouseInput:Y,SingleTouchInput:B,Recognizer:M,AttrRecognizer:L,Tap:V,Pan:U,Swipe:ea,Pinch:ba,Rotate:da,Press:ca,on:f,off:y,each:q,merge:Ca,extend:pa,assign:O,inherit:c,bindFn:a,
prefixed:k});("undefined"!==typeof p?p:"undefined"!==typeof self?self:{}).Hammer=N;"function"===typeof define&&define.amd?define(function(){return N}):"undefined"!=typeof A&&A.exports?A.exports=N:p[w]=N})(window,document,"Hammer")})()});require.register("marked/lib/marked.js",function(z,r,A){r=E(r,{},"marked");(function(){(function(p){function n(b){this.tokens=[];this.tokens.links={};this.options=b||y.defaults;this.rules=g.normal;this.options.gfm&&(this.rules=this.options.tables?g.tables:g.gfm)}function w(b,
a){this.options=a||y.defaults;this.links=b;this.rules=l.normal;this.renderer=this.options.renderer||new h;this.renderer.options=this.options;if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?l.breaks:l.gfm:this.options.pedantic&&(this.rules=l.pedantic)}function h(b){this.options=b||{}}function m(){}function x(b){this.tokens=[];this.token=null;this.options=b||y.defaults;this.options.renderer=this.options.renderer||new h;this.renderer=
this.options.renderer;this.renderer.options=this.options}function q(b,a){return b.replace(a?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function d(b){return b.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/ig,function(b,a){a=a.toLowerCase();return"colon"===a?":":"#"===a.charAt(0)?"x"===a.charAt(1)?String.fromCharCode(parseInt(a.substring(2),16)):String.fromCharCode(+a.substring(1)):""})}function c(b,a){b=b.source;
a=a||"";return{replace:function(a,c){c=c.source||c;c=c.replace(/(^|[^\[])\^/g,"$1");b=b.replace(a,c);return this},getRegex:function(){return new RegExp(b,a)}}}function a(b,a){u[" "+b]||(/^[^:]+:\/*[^/]*$/.test(b)?u[" "+b]=b+"/":u[" "+b]=b.replace(/[^/]*$/,""));b=u[" "+b];return"//"===a.slice(0,2)?b.replace(/:[\s\S]*/,":")+a:"/"===a.charAt(0)?b.replace(/(:\/*[^/]*)[\s\S]*/,"$1")+a:b+a}function v(){}function f(b){for(var a=1,c,g;a<arguments.length;a++)for(g in c=arguments[a],c)Object.prototype.hasOwnProperty.call(c,
g)&&(b[g]=c[g]);return b}function y(b,a,c){if("undefined"===typeof b||null===b)throw Error("marked(): input parameter is undefined or null");if("string"!==typeof b)throw Error("marked(): input parameter is of type "+Object.prototype.toString.call(b)+", string expected");if(c||"function"===typeof a){c||(c=a,a=null);a=f({},y.defaults,a||{});var k=a.highlight,g=0;try{var e=n.lex(b,a)}catch(K){return c(K)}var l=e.length;var d=function(b){if(b)return a.highlight=k,c(b);try{var g=x.parse(e,a)}catch(D){b=
D}a.highlight=k;return b?c(b):c(null,g)};if(!k||3>k.length)return d();delete a.highlight;if(!l)return d();for(;g<e.length;g++)(function(b){return"code"!==b.type?--l||d():k(b.text,b.lang,function(a,c){if(a)return d(a);if(null==c||c===b.text)return--l||d();b.text=c;b.escaped=!0;--l||d()})})(e[g])}else try{return a&&(a=f({},y.defaults,a)),x.parse(n.lex(b,a),a)}catch(K){K.message+="\nPlease report this to https://github.com/markedjs/marked.";if((a||y.defaults).silent)return"\x3cp\x3eAn error occurred:\x3c/p\x3e\x3cpre\x3e"+
q(K.message+"",!0)+"\x3c/pre\x3e";throw K;}}var g={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:v,hr:/^ {0,3}((?:- *){3,}|(?:_ *){3,}|(?:\* *){3,})(?:\n+|$)/,heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:v,blockquote:/^( {0,3}> ?(paragraph|[^\n]*)(?:\n|$))+/,list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ {0,3}\[(label)\]: *\n? *<?([^\s>]+)>?(?:(?: +\n? *| *\n *)(title))? *(?:\n+|$)/,
table:v,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,paragraph:/^([^\n]+(?:\n?(?!hr|heading|lheading| {0,3}>|tag)[^\n]+)+)/,text:/^[^\n]+/,_label:/(?:\\[\[\]]|[^\[\]])+/,_title:/(?:"(?:\\"|[^"]|"[^"\n]*")*"|'\n?(?:[^'\n]+\n?)*'|\([^()]*\))/};g.def=c(g.def).replace("label",g._label).replace("title",g._title).getRegex();g.bullet=/(?:[*+-]|\d+\.)/;g.item=/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/;g.item=c(g.item,"gm").replace(/bull/g,g.bullet).getRegex();g.list=c(g.list).replace(/bull/g,g.bullet).replace("hr",
"\\n+(?\x3d\\1?(?:(?:- *){3,}|(?:_ *){3,}|(?:\\* *){3,})(?:\\n+|$))").replace("def","\\n+(?\x3d"+g.def.source+")").getRegex();g._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:|[^\\w\\s@]*@)\\b";g.html=c(g.html).replace("comment",/\x3c!--[\s\S]*?--\x3e/).replace("closed",/<(tag)[\s\S]+?<\/\1>/).replace("closing",/<tag(?:"[^"]*"|'[^']*'|\s[^'"\/>\s]*)*?\/?>/).replace(/tag/g,g._tag).getRegex();g.paragraph=
c(g.paragraph).replace("hr",g.hr).replace("heading",g.heading).replace("lheading",g.lheading).replace("tag","\x3c"+g._tag).getRegex();g.blockquote=c(g.blockquote).replace("paragraph",g.paragraph).getRegex();g.normal=f({},g);g.gfm=f({},g.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\n? *\1 *(?:\n+|$)/,paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});g.gfm.paragraph=c(g.paragraph).replace("(?!","(?!"+g.gfm.fences.source.replace("\\1","\\2")+"|"+g.list.source.replace("\\1",
"\\3")+"|").getRegex();g.tables=f({},g.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});n.rules=g;n.lex=function(b,a){return(new n(a)).lex(b)};n.prototype.lex=function(b){b=b.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g," ").replace(/\u2424/g,"\n");return this.token(b,!0)};n.prototype.token=function(b,a){b=b.replace(/^ +$/gm,"");for(var c,k,e,l,d,f,u;b;){if(e=this.rules.newline.exec(b))b=
b.substring(e[0].length),1<e[0].length&&this.tokens.push({type:"space"});if(e=this.rules.code.exec(b))b=b.substring(e[0].length),e=e[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",text:this.options.pedantic?e:e.replace(/\n+$/,"")});else if(e=this.rules.fences.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"code",lang:e[2],text:e[3]||""});else if(e=this.rules.heading.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"heading",depth:e[1].length,text:e[2]});else if(a&&(e=this.rules.nptable.exec(b))){b=
b.substring(e[0].length);d={type:"table",header:e[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:e[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:e[3].replace(/\n$/,"").split("\n")};for(f=0;f<d.align.length;f++)/^ *-+: *$/.test(d.align[f])?d.align[f]="right":/^ *:-+: *$/.test(d.align[f])?d.align[f]="center":/^ *:-+ *$/.test(d.align[f])?d.align[f]="left":d.align[f]=null;for(f=0;f<d.cells.length;f++)d.cells[f]=d.cells[f].split(/ *\| */);this.tokens.push(d)}else if(e=this.rules.hr.exec(b))b=
b.substring(e[0].length),this.tokens.push({type:"hr"});else if(e=this.rules.blockquote.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"blockquote_start"}),e=e[0].replace(/^ *> ?/gm,""),this.token(e,a),this.tokens.push({type:"blockquote_end"});else if(e=this.rules.list.exec(b)){b=b.substring(e[0].length);l=e[2];c=1<l.length;this.tokens.push({type:"list_start",ordered:c,start:c?+l:""});e=e[0].match(this.rules.item);c=!1;u=e.length;for(f=0;f<u;f++)d=e[f],k=d.length,d=d.replace(/^ *([*+-]|\d+\.) +/,
""),~d.indexOf("\n ")&&(k-=d.length,d=this.options.pedantic?d.replace(/^ {1,4}/gm,""):d.replace(new RegExp("^ {1,"+k+"}","gm"),"")),this.options.smartLists&&f!==u-1&&(k=g.bullet.exec(e[f+1])[0],l===k||1<l.length&&1<k.length||(b=e.slice(f+1).join("\n")+b,f=u-1)),k=c||/\n\n(?!\s*$)/.test(d),f!==u-1&&(c="\n"===d.charAt(d.length-1),k||(k=c)),this.tokens.push({type:k?"loose_item_start":"list_item_start"}),this.token(d,!1),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(e=
this.rules.html.exec(b))b=b.substring(e[0].length),this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&("pre"===e[1]||"script"===e[1]||"style"===e[1]),text:e[0]});else if(a&&(e=this.rules.def.exec(b)))b=b.substring(e[0].length),e[3]&&(e[3]=e[3].substring(1,e[3].length-1)),l=e[1].toLowerCase(),this.tokens.links[l]||(this.tokens.links[l]={href:e[2],title:e[3]});else if(a&&(e=this.rules.table.exec(b))){b=b.substring(e[0].length);d={type:"table",header:e[1].replace(/^ *| *\| *$/g,
"").split(/ *\| */),align:e[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:e[3].replace(/(?: *\| *)?\n$/,"").split("\n")};for(f=0;f<d.align.length;f++)/^ *-+: *$/.test(d.align[f])?d.align[f]="right":/^ *:-+: *$/.test(d.align[f])?d.align[f]="center":/^ *:-+ *$/.test(d.align[f])?d.align[f]="left":d.align[f]=null;for(f=0;f<d.cells.length;f++)d.cells[f]=d.cells[f].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(d)}else if(e=this.rules.lheading.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"heading",
depth:"\x3d"===e[2]?1:2,text:e[1]});else if(a&&(e=this.rules.paragraph.exec(b)))b=b.substring(e[0].length),this.tokens.push({type:"paragraph",text:"\n"===e[1].charAt(e[1].length-1)?e[1].slice(0,-1):e[1]});else if(e=this.rules.text.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"text",text:e[0]});else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));}return this.tokens};var l={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<(scheme:[^\s\x00-\x1f<>]*|email)>/,url:v,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?[a-zA-Z0-9\-]+(?:"[^"]*"|'[^']*'|\s[^<'">\/\s]*)*?\/?>/,
link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,em:/^_([^\s_](?:[^_]|__)+?[^\s_])_\b|^\*((?:\*\*|[^*])+?)\*(?!\*)/,code:/^(`+)\s*([\s\S]*?[^`]?)\s*\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:v,text:/^[\s\S]+?(?=[\\<!\[`*]|\b_| {2,}\n|$)/,_scheme:/[a-zA-Z][a-zA-Z0-9+.-]{1,31}/,_email:/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(@)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_])/};
l.autolink=c(l.autolink).replace("scheme",l._scheme).replace("email",l._email).getRegex();l._inside=/(?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]]|\](?=[^\[]*\]))*/;l._href=/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/;l.link=c(l.link).replace("inside",l._inside).replace("href",l._href).getRegex();l.reflink=c(l.reflink).replace("inside",l._inside).getRegex();l.normal=f({},l);l.pedantic=f({},l.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});
l.gfm=f({},l.normal,{escape:c(l.escape).replace("])","~|])").getRegex(),url:c(/^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^email/).replace("email",l._email).getRegex(),_backpedal:/(?:[^?!.,:;*_~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_~)]+(?!$))+/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:c(l.text).replace("]|","~]|").replace("|","|https?://|ftp://|www\\.|[a-zA-Z0-9.!#$%\x26'*+/\x3d?^_`{\\|}~-]+@|").getRegex()});l.breaks=f({},l.gfm,{br:c(l.br).replace("{2,}","*").getRegex(),text:c(l.gfm.text).replace("{2,}",
"*").getRegex()});w.rules=l;w.output=function(b,a,c){return(new w(a,c)).output(b)};w.prototype.output=function(b){for(var a="",c,e;b;)if(e=this.rules.escape.exec(b))b=b.substring(e[0].length),a+=e[1];else if(e=this.rules.autolink.exec(b))b=b.substring(e[0].length),"@"===e[2]?(c=q(this.mangle(e[1])),e="mailto:"+c):e=c=q(e[1]),a+=this.renderer.link(e,null,c);else if(!this.inLink&&(e=this.rules.url.exec(b)))e[0]=this.rules._backpedal.exec(e[0])[0],b=b.substring(e[0].length),"@"===e[2]?(c=q(e[0]),e="mailto:"+
c):(c=q(e[0]),e="www."===e[1]?"http://"+c:c),a+=this.renderer.link(e,null,c);else if(e=this.rules.tag.exec(b))!this.inLink&&/^<a /i.test(e[0])?this.inLink=!0:this.inLink&&/^<\/a>/i.test(e[0])&&(this.inLink=!1),b=b.substring(e[0].length),a+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(e[0]):q(e[0]):e[0];else if(e=this.rules.link.exec(b))b=b.substring(e[0].length),this.inLink=!0,a+=this.outputLink(e,{href:e[2],title:e[3]}),this.inLink=!1;else if((e=this.rules.reflink.exec(b))||
(e=this.rules.nolink.exec(b)))b=b.substring(e[0].length),c=(e[2]||e[1]).replace(/\s+/g," "),(c=this.links[c.toLowerCase()])&&c.href?(this.inLink=!0,a+=this.outputLink(e,c),this.inLink=!1):(a+=e[0].charAt(0),b=e[0].substring(1)+b);else if(e=this.rules.strong.exec(b))b=b.substring(e[0].length),a+=this.renderer.strong(this.output(e[2]||e[1]));else if(e=this.rules.em.exec(b))b=b.substring(e[0].length),a+=this.renderer.em(this.output(e[2]||e[1]));else if(e=this.rules.code.exec(b))b=b.substring(e[0].length),
a+=this.renderer.codespan(q(e[2].trim(),!0));else if(e=this.rules.br.exec(b))b=b.substring(e[0].length),a+=this.renderer.br();else if(e=this.rules.del.exec(b))b=b.substring(e[0].length),a+=this.renderer.del(this.output(e[1]));else if(e=this.rules.text.exec(b))b=b.substring(e[0].length),a+=this.renderer.text(q(this.smartypants(e[0])));else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));return a};w.prototype.outputLink=function(b,a){var c=q(a.href);a=a.title?q(a.title):null;return"!"!==
b[0].charAt(0)?this.renderer.link(c,a,this.output(b[1])):this.renderer.image(c,a,q(b[1]))};w.prototype.smartypants=function(b){return this.options.smartypants?b.replace(/---/g,"\u2014").replace(/--/g,"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,"\u201d").replace(/\.{3}/g,"\u2026"):b};w.prototype.mangle=function(b){if(!this.options.mangle)return b;for(var a="",c=b.length,e=0,g;e<c;e++)g=b.charCodeAt(e),
.5<Math.random()&&(g="x"+g.toString(16)),a+="\x26#"+g+";";return a};h.prototype.code=function(b,a,c){if(this.options.highlight){var e=this.options.highlight(b,a);null!=e&&e!==b&&(c=!0,b=e)}return a?'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+q(a,!0)+'"\x3e'+(c?b:q(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+(c?b:q(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};h.prototype.blockquote=function(b){return"\x3cblockquote\x3e\n"+b+"\x3c/blockquote\x3e\n"};h.prototype.html=function(b){return b};
h.prototype.heading=function(b,a,c){return"\x3ch"+a+' id\x3d"'+this.options.headerPrefix+c.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+b+"\x3c/h"+a+"\x3e\n"};h.prototype.hr=function(){return this.options.xhtml?"\x3chr/\x3e\n":"\x3chr\x3e\n"};h.prototype.list=function(b,a,c){var e=a?"ol":"ul";return"\x3c"+e+(a&&1!==c?' start\x3d"'+c+'"':"")+"\x3e\n"+b+"\x3c/"+e+"\x3e\n"};h.prototype.listitem=function(b){return"\x3cli\x3e"+b+"\x3c/li\x3e\n"};h.prototype.paragraph=function(b){return"\x3cp\x3e"+b+"\x3c/p\x3e\n"};
h.prototype.table=function(b,a){return"\x3ctable\x3e\n\x3cthead\x3e\n"+b+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+a+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};h.prototype.tablerow=function(b){return"\x3ctr\x3e\n"+b+"\x3c/tr\x3e\n"};h.prototype.tablecell=function(b,a){var c=a.header?"th":"td";return(a.align?"\x3c"+c+' style\x3d"text-align:'+a.align+'"\x3e':"\x3c"+c+"\x3e")+b+"\x3c/"+c+"\x3e\n"};h.prototype.strong=function(b){return"\x3cstrong\x3e"+b+"\x3c/strong\x3e"};h.prototype.em=function(b){return"\x3cem\x3e"+
b+"\x3c/em\x3e"};h.prototype.codespan=function(b){return"\x3ccode\x3e"+b+"\x3c/code\x3e"};h.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};h.prototype.del=function(b){return"\x3cdel\x3e"+b+"\x3c/del\x3e"};h.prototype.link=function(b,c,g){if(this.options.sanitize){try{var k=decodeURIComponent(d(b)).replace(/[^\w:]/g,"").toLowerCase()}catch(I){return g}if(0===k.indexOf("javascript:")||0===k.indexOf("vbscript:")||0===k.indexOf("data:"))return g}this.options.baseUrl&&!e.test(b)&&
(b=a(this.options.baseUrl,b));b='\x3ca href\x3d"'+b+'"';c&&(b+=' title\x3d"'+c+'"');return b+("\x3e"+g+"\x3c/a\x3e")};h.prototype.image=function(b,c,g){this.options.baseUrl&&!e.test(b)&&(b=a(this.options.baseUrl,b));b='\x3cimg src\x3d"'+b+'" alt\x3d"'+g+'"';c&&(b+=' title\x3d"'+c+'"');return b+=this.options.xhtml?"/\x3e":"\x3e"};h.prototype.text=function(b){return b};m.prototype.strong=m.prototype.em=m.prototype.codespan=m.prototype.del=m.prototype.text=function(b){return b};m.prototype.link=m.prototype.image=
function(b,a,c){return""+c};m.prototype.br=function(){return""};x.parse=function(b,a){return(new x(a)).parse(b)};x.prototype.parse=function(b){this.inline=new w(b.links,this.options);this.inlineText=new w(b.links,f({},this.options,{renderer:new m}));this.tokens=b.reverse();for(b="";this.next();)b+=this.tok();return b};x.prototype.next=function(){return this.token=this.tokens.pop()};x.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};x.prototype.parseText=function(){for(var b=
this.token.text;"text"===this.peek().type;)b+="\n"+this.next().text;return this.inline.output(b)};x.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return this.renderer.hr();case "heading":return this.renderer.heading(this.inline.output(this.token.text),this.token.depth,d(this.inlineText.output(this.token.text)));case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);case "table":var b="";var a="";var c,e;var g="";for(c=0;c<this.token.header.length;c++)g+=
this.renderer.tablecell(this.inline.output(this.token.header[c]),{header:!0,align:this.token.align[c]});b+=this.renderer.tablerow(g);for(c=0;c<this.token.cells.length;c++){var l=this.token.cells[c];g="";for(e=0;e<l.length;e++)g+=this.renderer.tablecell(this.inline.output(l[e]),{header:!1,align:this.token.align[e]});a+=this.renderer.tablerow(g)}return this.renderer.table(b,a);case "blockquote_start":for(a="";"blockquote_end"!==this.next().type;)a+=this.tok();return this.renderer.blockquote(a);case "list_start":a=
"";b=this.token.ordered;for(c=this.token.start;"list_end"!==this.next().type;)a+=this.tok();return this.renderer.list(a,b,c);case "list_item_start":for(a="";"list_item_end"!==this.next().type;)a+="text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(a);case "loose_item_start":for(a="";"list_item_end"!==this.next().type;)a+=this.tok();return this.renderer.listitem(a);case "html":return a=this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text),
this.renderer.html(a);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};var u={},e=/^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;v.exec=v;y.options=y.setOptions=function(b){f(y.defaults,b);return y};y.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new h,xhtml:!1,baseUrl:null};y.Parser=
x;y.parser=x.parse;y.Renderer=h;y.TextRenderer=m;y.Lexer=n;y.lexer=n.lex;y.InlineLexer=w;y.inlineLexer=w.output;y.parse=y;"undefined"!==typeof A&&"object"===typeof z?A.exports=y:"function"===typeof define&&define.amd?define(function(){return y}):p.marked=y})(this||("undefined"!==typeof window?window:p))})()});require.register("prismjs/prism.js",function(z,r,A){r=E(r,{},"prismjs");(function(){var r="undefined"!==typeof window?window:"undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?
self:{},n=function(){var p=/\blang(?:uage)?-([\w-]+)\b/i,h=0,m=r.Prism={manual:r.Prism&&r.Prism.manual,disableWorkerMessageHandler:r.Prism&&r.Prism.disableWorkerMessageHandler,util:{encode:function(d){return d instanceof n?new n(d.type,m.util.encode(d.content),d.alias):"Array"===m.util.type(d)?d.map(m.util.encode):d.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/\u00a0/g," ")},type:function(d){return Object.prototype.toString.call(d).match(/\[object (\w+)\]/)[1]},objId:function(d){d.__id||
Object.defineProperty(d,"__id",{value:++h});return d.__id},clone:function(d,c){var a=m.util.type(d);c=c||{};switch(a){case "Object":if(c[m.util.objId(d)])return c[m.util.objId(d)];var h={};c[m.util.objId(d)]=h;for(var f in d)d.hasOwnProperty(f)&&(h[f]=m.util.clone(d[f],c));return h;case "Array":if(c[m.util.objId(d)])return c[m.util.objId(d)];h=[];c[m.util.objId(d)]=h;d.forEach(function(a,g){h[g]=m.util.clone(a,c)});return h}return d}},languages:{extend:function(d,c){d=m.util.clone(m.languages[d]);
for(var a in c)d[a]=c[a];return d},insertBefore:function(d,c,a,h){h=h||m.languages;var f=h[d];if(2==arguments.length){a=arguments[1];for(var n in a)a.hasOwnProperty(n)&&(f[n]=a[n]);return f}var g={},l;for(l in f)if(f.hasOwnProperty(l)){if(l==c)for(n in a)a.hasOwnProperty(n)&&(g[n]=a[n]);g[l]=f[l]}m.languages.DFS(m.languages,function(a,c){c===h[d]&&a!=d&&(this[a]=g)});return h[d]=g},DFS:function(d,c,a,h){h=h||{};for(var f in d)d.hasOwnProperty(f)&&((c.call(d,f,d[f],a||f),"Object"!==m.util.type(d[f])||
h[m.util.objId(d[f])])?"Array"!==m.util.type(d[f])||h[m.util.objId(d[f])]||(h[m.util.objId(d[f])]=!0,m.languages.DFS(d[f],c,f,h)):(h[m.util.objId(d[f])]=!0,m.languages.DFS(d[f],c,null,h)))}},plugins:{},highlightAll:function(d,c){m.highlightAllUnder(document,d,c)},highlightAllUnder:function(d,c,a){a={callback:a,selector:'code[class*\x3d"language-"], [class*\x3d"language-"] code, code[class*\x3d"lang-"], [class*\x3d"lang-"] code'};m.hooks.run("before-highlightall",a);d=a.elements||d.querySelectorAll(a.selector);
for(var h=0,f;f=d[h++];)m.highlightElement(f,!0===c,a.callback)},highlightElement:function(d,c,a){for(var h,f,n=d;n&&!p.test(n.className);)n=n.parentNode;n&&(h=(n.className.match(p)||[,""])[1].toLowerCase(),f=m.languages[h]);d.className=d.className.replace(p,"").replace(/\s+/g," ")+" language-"+h;d.parentNode&&(n=d.parentNode,/pre/i.test(n.nodeName)&&(n.className=n.className.replace(p,"").replace(/\s+/g," ")+" language-"+h));var g={element:d,language:h,grammar:f,code:d.textContent};m.hooks.run("before-sanity-check",
g);g.code&&g.grammar?(m.hooks.run("before-highlight",g),c&&r.Worker?(d=new Worker(m.filename),d.onmessage=function(c){g.highlightedCode=c.data;m.hooks.run("before-insert",g);g.element.innerHTML=g.highlightedCode;a&&a.call(g.element);m.hooks.run("after-highlight",g);m.hooks.run("complete",g)},d.postMessage(JSON.stringify({language:g.language,code:g.code,immediateClose:!0}))):(g.highlightedCode=m.highlight(g.code,g.grammar,g.language),m.hooks.run("before-insert",g),g.element.innerHTML=g.highlightedCode,
a&&a.call(d),m.hooks.run("after-highlight",g),m.hooks.run("complete",g))):(g.code&&(m.hooks.run("before-highlight",g),g.element.textContent=g.code,m.hooks.run("after-highlight",g)),m.hooks.run("complete",g))},highlight:function(d,c,a){d={code:d,grammar:c,language:a};m.hooks.run("before-tokenize",d);d.tokens=m.tokenize(d.code,d.grammar);m.hooks.run("after-tokenize",d);return n.stringify(m.util.encode(d.tokens),d.language)},matchGrammar:function(d,c,a,h,f,n,g){var l=m.Token,u;for(u in a)if(a.hasOwnProperty(u)&&
a[u]){if(u==g)break;var e=a[u];e="Array"===m.util.type(e)?e:[e];for(var b=0;b<e.length;++b){var k=e[b],p=k.inside,C=!!k.lookbehind,q=!!k.greedy,v=0,G=k.alias;if(q&&!k.pattern.global){var F=k.pattern.toString().match(/[imuy]*$/)[0];k.pattern=RegExp(k.pattern.source,F+"g")}k=k.pattern||k;F=h;for(var y=f;F<c.length;y+=c[F].length,++F){var r=c[F];if(c.length>d.length)return;if(!(r instanceof l)){if(q&&F!=c.length-1){k.lastIndex=y;var D=k.exec(d);if(!D)break;var x=D.index+(C?D[1].length:0);var w=D.index+
D[0].length;var z=F;r=y;for(var A=c.length;z<A&&(r<w||!c[z].type&&!c[z-1].greedy);++z)r+=c[z].length,x>=r&&(++F,y=r);if(c[F]instanceof l)continue;z-=F;r=d.slice(y,r);D.index-=y}else k.lastIndex=0,D=k.exec(r),z=1;D&&(C&&(v=D[1]?D[1].length:0),x=D.index+v,D=D[0].slice(v),w=x+D.length,x=r.slice(0,x),w=r.slice(w),r=[F,z],x&&(++F,y+=x.length,r.push(x)),D=new l(u,p?m.tokenize(D,p):D,G,D,q),r.push(D),w&&r.push(w),Array.prototype.splice.apply(c,r),1!=z&&m.matchGrammar(d,c,a,F,y,!0,u));if(n)break}}}}},tokenize:function(d,
c,a){a=[d];var h=c.rest;if(h){for(var f in h)c[f]=h[f];delete c.rest}m.matchGrammar(d,a,c,0,0,!1);return a},hooks:{all:{},add:function(d,c){var a=m.hooks.all;a[d]=a[d]||[];a[d].push(c)},run:function(d,c){if((d=m.hooks.all[d])&&d.length)for(var a=0,h;h=d[a++];)h(c)}}},n=m.Token=function(d,c,a,m,f){this.type=d;this.content=c;this.alias=a;this.length=(m||"").length|0;this.greedy=!!f};n.stringify=function(d,c,a){if("string"==typeof d)return d;if("Array"===m.util.type(d))return d.map(function(a){return n.stringify(a,
c,d)}).join("");var h={type:d.type,content:n.stringify(d.content,c,a),tag:"span",classes:["token",d.type],attributes:{},language:c,parent:a};d.alias&&(a="Array"===m.util.type(d.alias)?d.alias:[d.alias],Array.prototype.push.apply(h.classes,a));m.hooks.run("wrap",h);a=Object.keys(h.attributes).map(function(a){return a+'\x3d"'+(h.attributes[a]||"").replace(/"/g,"\x26quot;")+'"'}).join(" ");return"\x3c"+h.tag+' class\x3d"'+h.classes.join(" ")+'"'+(a?" "+a:"")+"\x3e"+h.content+"\x3c/"+h.tag+"\x3e"};if(!r.document){if(!r.addEventListener)return r.Prism;
m.disableWorkerMessageHandler||r.addEventListener("message",function(d){d=JSON.parse(d.data);var c=d.language,a=d.immediateClose;r.postMessage(m.highlight(d.code,m.languages[c],c));a&&r.close()},!1);return r.Prism}var q=document.currentScript||[].slice.call(document.getElementsByTagName("script")).pop();q&&(m.filename=q.src,m.manual||q.hasAttribute("data-manual")||("loading"!==document.readyState?window.requestAnimationFrame?window.requestAnimationFrame(m.highlightAll):window.setTimeout(m.highlightAll,
16):document.addEventListener("DOMContentLoaded",m.highlightAll)));return r.Prism}();"undefined"!==typeof A&&A.exports&&(A.exports=n);"undefined"!==typeof p&&(p.Prism=n);n.languages.markup={comment:/\x3c!--[\s\S]*?--\x3e/,prolog:/<\?[\s\S]+?\?>/,doctype:/<!DOCTYPE[\s\S]+?>/i,cdata:/<!\[CDATA\[[\s\S]*?]]\x3e/i,tag:{pattern:/<\/?(?!\d)[^\s>\/=$<%]+(?:\s+[^\s>\/=]+(?:=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+))?)*\s*\/?>/i,greedy:!0,inside:{tag:{pattern:/^<\/?[^\s>\/]+/i,inside:{punctuation:/^<\/?/,
namespace:/^[^\s>\/:]+:/}},"attr-value":{pattern:/=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+)/i,inside:{punctuation:[/^=/,{pattern:/(^|[^\\])["']/,lookbehind:!0}]}},punctuation:/\/?>/,"attr-name":{pattern:/[^\s>\/]+/,inside:{namespace:/^[^\s>\/:]+:/}}}},entity:/&#?[\da-z]{1,8};/i};n.languages.markup.tag.inside["attr-value"].inside.entity=n.languages.markup.entity;n.hooks.add("wrap",function(n){"entity"===n.type&&(n.attributes.title=n.content.replace(/&amp;/,"\x26"))});n.languages.xml=n.languages.markup;
n.languages.html=n.languages.markup;n.languages.mathml=n.languages.markup;n.languages.svg=n.languages.markup;n.languages.css={comment:/\/\*[\s\S]*?\*\//,atrule:{pattern:/@[\w-]+?.*?(?:;|(?=\s*\{))/i,inside:{rule:/@[\w-]+/}},url:/url\((?:(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1|.*?)\)/i,selector:/[^{}\s][^{};]*?(?=\s*\{)/,string:{pattern:/("|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},property:/[-_a-z\xA0-\uFFFF][-\w\xA0-\uFFFF]*(?=\s*:)/i,important:/\B!important\b/i,"function":/[-a-z0-9]+(?=\()/i,
punctuation:/[(){};:]/};n.languages.css.atrule.inside.rest=n.languages.css;n.languages.markup&&(n.languages.insertBefore("markup","tag",{style:{pattern:/(<style[\s\S]*?>)[\s\S]*?(?=<\/style>)/i,lookbehind:!0,inside:n.languages.css,alias:"language-css",greedy:!0}}),n.languages.insertBefore("inside","attr-value",{"style-attr":{pattern:/\s*style=("|')(?:\\[\s\S]|(?!\1)[^\\])*\1/i,inside:{"attr-name":{pattern:/^\s*style/i,inside:n.languages.markup.tag.inside},punctuation:/^\s*=\s*['"]|['"]\s*$/,"attr-value":{pattern:/.+/i,
inside:n.languages.css}},alias:"language-css"}},n.languages.markup.tag));n.languages.clike={comment:[{pattern:/(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,lookbehind:!0},{pattern:/(^|[^\\:])\/\/.*/,lookbehind:!0,greedy:!0}],string:{pattern:/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},"class-name":{pattern:/((?:\b(?:class|interface|extends|implements|trait|instanceof|new)\s+)|(?:catch\s+\())[\w.\\]+/i,lookbehind:!0,inside:{punctuation:/[.\\]/}},keyword:/\b(?:if|else|while|do|for|return|in|instanceof|function|new|try|throw|catch|finally|null|break|continue)\b/,
"boolean":/\b(?:true|false)\b/,"function":/[a-z0-9_]+(?=\()/i,number:/\b0x[\da-f]+\b|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?/i,operator:/--?|\+\+?|!=?=?|<=?|>=?|==?=?|&&?|\|\|?|\?|\*|\/|~|\^|%/,punctuation:/[{}[\];(),.:]/};n.languages.javascript=n.languages.extend("clike",{keyword:/\b(?:as|async|await|break|case|catch|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally|for|from|function|get|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|set|static|super|switch|this|throw|try|typeof|var|void|while|with|yield)\b/,
number:/\b(?:0[xX][\dA-Fa-f]+|0[bB][01]+|0[oO][0-7]+|NaN|Infinity)\b|(?:\b\d+\.?\d*|\B\.\d+)(?:[Ee][+-]?\d+)?/,"function":/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*\()/i,operator:/-[-=]?|\+[+=]?|!=?=?|<<?=?|>>?>?=?|=(?:==?|>)?|&[&=]?|\|[|=]?|\*\*?=?|\/=?|~|\^=?|%=?|\?|\.{3}/});n.languages.insertBefore("javascript","keyword",{regex:{pattern:/((?:^|[^$\w\xA0-\uFFFF."'\])\s])\s*)\/(\[[^\]\r\n]+]|\\.|[^/\\\[\r\n])+\/[gimyu]{0,5}(?=\s*($|[\r\n,.;})]))/,lookbehind:!0,greedy:!0},"function-variable":{pattern:/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*=\s*(?:function\b|(?:\([^()]*\)|[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*)\s*=>))/i,
alias:"function"},constant:/\b[A-Z][A-Z\d_]*\b/});n.languages.insertBefore("javascript","string",{"template-string":{pattern:/`(?:\\[\s\S]|[^\\`])*`/,greedy:!0,inside:{interpolation:{pattern:/\$\{[^}]+\}/,inside:{"interpolation-punctuation":{pattern:/^\$\{|\}$/,alias:"punctuation"},rest:n.languages.javascript}},string:/[\s\S]+/}}});n.languages.markup&&n.languages.insertBefore("markup","tag",{script:{pattern:/(<script[\s\S]*?>)[\s\S]*?(?=<\/script>)/i,lookbehind:!0,inside:n.languages.javascript,alias:"language-javascript",
greedy:!0}});n.languages.js=n.languages.javascript;(function(){"undefined"!==typeof self&&self.Prism&&self.document&&document.querySelector&&(self.Prism.fileHighlight=function(){var p={js:"javascript",py:"python",rb:"ruby",ps1:"powershell",psm1:"powershell",sh:"bash",bat:"batch",h:"c",tex:"latex"};Array.prototype.slice.call(document.querySelectorAll("pre[data-src]")).forEach(function(h){for(var m=h.getAttribute("data-src"),r,q=h,d=/\blang(?:uage)?-(?!\*)([\w-]+)\b/i;q&&!d.test(q.className);)q=q.parentNode;
q&&(r=(h.className.match(d)||[,""])[1]);r||(r=(m.match(/\.(\w+)$/)||[,""])[1],r=p[r]||r);var c=document.createElement("code");c.className="language-"+r;h.textContent="";c.textContent="Loading\u2026";h.appendChild(c);var a=new XMLHttpRequest;a.open("GET",m,!0);a.onreadystatechange=function(){4==a.readyState&&(400>a.status&&a.responseText?(c.textContent=a.responseText,n.highlightElement(c)):c.textContent=400<=a.status?"\u2716 Error "+a.status+" while fetching file: "+a.statusText:"\u2716 Error: File does not exist or is empty")};
h.hasAttribute("data-download-link")&&n.plugins.toolbar&&n.plugins.toolbar.registerButton("download-file",function(){var a=document.createElement("a");a.textContent=h.getAttribute("data-download-link-label")||"Download";a.setAttribute("download","");a.href=m;return a});a.send(null)})},document.addEventListener("DOMContentLoaded",self.Prism.fileHighlight))})()})()});require.register("components/main.component.svelte",function(p,r,A){function z(g,l){var d,e,b,k,f,h,m,n,p=new a({root:g.root});p.on("mobilemenu",
function(b){g.handleMobileMenu(b)});p.on("fontsize",function(b){g.handleFontSize(b)});g.refs.topbar=p;var q=new c({root:g.root});q.on("mobilemenu",function(b){g.handleMobileMenu(b)});g.refs.menu=q;return{c:function(){d=document.createElement("div");p._fragment.c();e=document.createTextNode("\n  ");q._fragment.c();b=document.createTextNode("\n  ");k=document.createElement("div");f=document.createElement("div");h=document.createTextNode("\n    ");m=document.createElement("div");this.h()},h:function(){f.className=
"menu-swipper";m.className=n="doc-container font-"+l.fontSize;k.className="body";d.className="MainComp"},m:function(a,c){a.insertBefore(d,c);p._mount(d,null);d.appendChild(e);q._mount(d,null);d.appendChild(b);d.appendChild(k);k.appendChild(f);k.appendChild(h);k.appendChild(m);m.innerHTML=l.documentationHTML;g.refs.docContainer=m},p:function(b,a){b.documentationHTML&&(m.innerHTML=a.documentationHTML);b.fontSize&&n!==(n="doc-container font-"+a.fontSize)&&(m.className=n)},u:function(){m.innerHTML="";
d.parentNode.removeChild(d)},d:function(){p.destroy(!1);g.refs.topbar===p&&(g.refs.topbar=null);q.destroy(!1);g.refs.menu===q&&(g.refs.menu=null);g.refs.docContainer===m&&(g.refs.docContainer=null)}}}function n(a){w(this,a);this.refs={};this._state=h({fontSize:2,documentation:"",documentationHTML:""},a.data);var c=this;a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);this.root._oncreate.push(function(){c.registerDocumentation();c.fire("update",
{changed:{fontSize:1,documentationHTML:1},current:c._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,m(this._beforecreate),m(this._oncreate),m(this._aftercreate),this._lock=!1)}function w(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function h(a,c){for(var g in c)a[g]=c[g];return a}function m(a){for(;a&&a.length;)a.shift()()}function x(a){this.destroy=q;this.fire("destroy");this.set=this.get=q;
!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function q(){}var d=r("../herodotus-settings.js"),c=r("./menu.component"),a=r("./topbar.component"),v=r("marked"),f=r("@fdaciuk/ajax");r("hammerjs");var y=r("prismjs");d=d&&d.__esModule?d["default"]:d;c=c&&c.__esModule?c["default"]:c;a=a&&a.__esModule?a["default"]:a;v=v&&v.__esModule?v["default"]:v;f=f&&f.__esModule?f["default"]:f;y=y&&y.__esModule?y["default"]:y;h(n.prototype,{destroy:x,get:function(a){return a?this._state[a]:
this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var g=0;g<a.length;g+=1){var e=a[g];e.__calling||(e.__calling=!0,e.call(this,c),e.__calling=!1)}},observe:function(a,c,d){var e=c.bind(this);d&&!1===d.init||e(this.get()[a],void 0);return this.on(d&&d.defer?"update":"state",function(b){b.changed[a]&&e(b.current[a],b.previous&&b.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var d=this._handlers[a]||(this._handlers[a]=[]);d.push(c);
return{cancel:function(){var a=d.indexOf(c);~a&&d.splice(a,1)}}},set:function(a){this._set(h({},a));this.root._lock||(this.root._lock=!0,m(this.root._beforecreate),m(this.root._oncreate),m(this.root._aftercreate),this.root._lock=!1)},teardown:x,_set:function(a){var c=this._state,d={},e=!1,b;for(b in a)this._differs(a[b],c[b])&&(d[b]=e=!0);e&&(this._state=h(h({},c),a),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&(this.fire("state",{changed:d,current:this._state,
previous:c}),this._fragment.p(d,this._state),this.fire("update",{changed:d,current:this._state,previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});h(n.prototype,{getParentId:function(a){return"end"===a?null:a.id&&-1<["H1","H2"].indexOf(a.tagName)?{id:a.id,title:a.textContent}:this.getParentId(a.previousElementSibling||
"end")},generateSearchList:function(){var a=this,c=[];[].concat($jscomp.arrayFromIterable(document.querySelector(".doc-container").children)).forEach(function(d){var e=a.getParentId(d);e&&c.push({id:e.id,title:e.title,content:d.textContent})});return c},handleFontSize:function(a){switch(a.action){case "INCREASE":this.increaseFont();break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(a){switch(a.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});break;
case "CLOSE":this.refs.menu.close();this.refs.topbar.set({isMenuOpen:!1});break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var a=this.get("fontSize");4<=a||this.set({fontSize:a+1})},decreaseFont:function(){var a=this.get("fontSize");1>=a||this.set({fontSize:a-1})},registerDocumentation:function(){var a=this;var c=d.allow_remote_documentation?d.remote_documentation_url:"documentation.md";f().get(c).then(function(c,e){a.set({documentation:c,documentationHTML:v(c)});
a.refs.menu.startMenu(a.generateMenu());a.refs.topbar.refs.searchlist.set({searchList:a.generateSearchList()});y.highlightAll()})},generateMenu:function(){var a=[],c=[],d;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(e){c.push({type:e.nodeName.toLowerCase(),label:e.textContent,id:e.id});"h1"===e.nodeName.toLowerCase()?(a.push({type:e.nodeName.toLowerCase(),label:e.textContent,id:e.id}),d=a[a.length-1],d.children=[]):"h2"===e.nodeName.toLowerCase()&&d.children.push({type:e.nodeName.toLowerCase(),
label:e.textContent,id:e.id})});return{menuItems:a,menuItemsFlat:c}}});n.prototype._recompute=q;A.exports=n});require.register("components/menu.component.svelte",function(p,r,A){function z(a,b){(new u(a)).on("swipeleft",b)}function n(){var a=this;window.onhashchange=function(){a.scrollToURLMenu()}}function w(c,b){function e(b){c.onAppScroll(this.scrollY)}function d(b){c.fire("mobilemenu",{action:"CLOSE"})}var f,g,l,m,n,u,p,q,r,y;window.addEventListener("scroll",e);for(var x=b.menuItems,w=[],A=0;A<
x.length;A+=1)w[A]=h(c,a(a({},b),{each_value:x,item:x[A],item_index:A}));return{c:function(){f=document.createElement("div");g=document.createElement("div");m=document.createTextNode("\n  ");n=document.createElement("div");u=document.createElement("img");p=document.createTextNode("\n    ");q=document.createElement("ul");for(var b=0;b<w.length;b+=1)w[b].c();this.h()},h:function(){g.addEventListener("click",d,!1);g.className=l="MenuComp--overlay "+(b.isOpen?"active":"");u.src="img/logo-dark.svg";u.alt=
"UnoCode Docs";u.className="logo";q.className="menu";r=z.call(c,n,function(b){c.fire("mobilemenu",{action:"CLOSE"})});n.className=y="MenuComp "+(b.isOpen?"open":"")},m:function(b,a){b.insertBefore(f,a);f.appendChild(g);c.refs.overlay=g;f.appendChild(m);f.appendChild(n);n.appendChild(u);n.appendChild(p);n.appendChild(q);for(b=0;b<w.length;b+=1)w[b].m(q,null);c.refs.menu=n},p:function(b,e){b.isOpen&&l!==(l="MenuComp--overlay "+(e.isOpen?"active":""))&&(g.className=l);var d=e.menuItems;if(b.menuItems){for(var k=
0;k<d.length;k+=1){var f=a(a({},e),{each_value:d,item:d[k],item_index:k});w[k]?w[k].p(b,f):(w[k]=h(c,f),w[k].c(),w[k].m(q,null))}for(;k<w.length;k+=1)w[k].u(),w[k].d();w.length=d.length}b.isOpen&&y!==(y="MenuComp "+(e.isOpen?"open":""))&&(n.className=y)},u:function(){f.parentNode.removeChild(f);for(var b=0;b<w.length;b+=1)w[b].u()},d:function(){window.removeEventListener("scroll",e);g.removeEventListener("click",d,!1);c.refs.overlay===g&&(c.refs.overlay=null);v(w);r[r.destroy?"destroy":"teardown"]();
c.refs.menu===n&&(c.refs.menu=null)}}}function h(a,b){var c=b.item,e,d,f=c.label,g,l,m,h,n,u=0<c.children.length&&x(a,b);return{c:function(){e=document.createElement("li");d=document.createElement("a");g=document.createTextNode(f);m=document.createTextNode("\n            ");u&&u.c();this.h()},h:function(){d.addEventListener("click",q,!1);d.href=l="#"+c.id;d._svelte={component:a,each_value:b.each_value,item_index:b.item_index};e.id=h="menu-"+c.id;e.className=n=c.type},m:function(b,a){b.insertBefore(e,
a);e.appendChild(d);d.appendChild(g);e.appendChild(m);u&&u.m(e,null)},p:function(b,k){c=k.item;b.menuItems&&f!==(f=c.label)&&(g.data=f);b.menuItems&&l!==(l="#"+c.id)&&(d.href=l);d._svelte.each_value=k.each_value;d._svelte.item_index=k.item_index;0<c.children.length?u?u.p(b,k):(u=x(a,k),u.c(),u.m(e,null)):u&&(u.u(),u.d(),u=null);b.menuItems&&h!==(h="menu-"+c.id)&&(e.id=h);b.menuItems&&n!==(n=c.type)&&(e.className=n)},u:function(){e.parentNode.removeChild(e);u&&u.u()},d:function(){d.removeEventListener("click",
q,!1);u&&u.d()}}}function m(a,b){var c=b.subitem,e,f,g=c.label,l,m,h,n;return{c:function(){e=document.createElement("li");f=document.createElement("a");l=document.createTextNode(g);this.h()},h:function(){f.addEventListener("click",d,!1);f.href=m="#"+c.id;f._svelte={component:a,each_value_1:b.each_value_1,subitem_index:b.subitem_index};e.id=h="menu-"+c.id;e.className=n=c.type},m:function(b,a){b.insertBefore(e,a);e.appendChild(f);f.appendChild(l)},p:function(b,a){c=a.subitem;b.menuItems&&g!==(g=c.label)&&
(l.data=g);b.menuItems&&m!==(m="#"+c.id)&&(f.href=m);f._svelte.each_value_1=a.each_value_1;f._svelte.subitem_index=a.subitem_index;b.menuItems&&h!==(h="menu-"+c.id)&&(e.id=h);b.menuItems&&n!==(n=c.type)&&(e.className=n)},u:function(){e.parentNode.removeChild(e)},d:function(){f.removeEventListener("click",d,!1)}}}function x(c,b){for(var e=b.item,d,f=e.children,g=[],l=0;l<f.length;l+=1)g[l]=m(c,a(a({},b),{each_value_1:f,subitem:f[l],subitem_index:l}));return{c:function(){d=document.createElement("ul");
for(var b=0;b<g.length;b+=1)g[b].c();this.h()},h:function(){d.className="subsection"},m:function(b,a){b.insertBefore(d,a);for(b=0;b<g.length;b+=1)g[b].m(d,null)},p:function(b,f){e=f.item;var k=e.children;if(b.menuItems){for(var l=0;l<k.length;l+=1){var h=a(a({},f),{each_value_1:k,subitem:k[l],subitem_index:l});g[l]?g[l].p(b,h):(g[l]=m(c,h),g[l].c(),g[l].m(d,null))}for(;l<g.length;l+=1)g[l].u(),g[l].d();g.length=k.length}},u:function(){d.parentNode.removeChild(d);for(var b=0;b<g.length;b+=1)g[b].u()},
d:function(){v(g)}}}function q(a){this._svelte.component.scrollToItem(this._svelte.each_value[this._svelte.item_index],a)}function d(a){this._svelte.component.scrollToItem(this._svelte.each_value_1[this._svelte.subitem_index],a)}function c(c){f(this,c);this.refs={};this._state=a({menuItems:[],menuItemsFlat:[],isOpen:!1,prevY:0},c.data);var b=this;c.root||(this._oncreate=[]);this._fragment=w(this,this._state);this.root._oncreate.push(function(){n.call(b);b.fire("update",{changed:{isOpen:1,menuItems:1},
current:b._state})});c.target&&(this._fragment.c(),this._mount(c.target,c.anchor),y(this._oncreate))}function a(a,b){for(var c in b)a[c]=b[c];return a}function v(a){for(var b=0;b<a.length;b+=1)a[b]&&a[b].d()}function f(a,b){a._handlers=Object.create(null);a._bind=b._bind;a.options=b;a.root=b.root||a;a.store=a.root.store||b.store}function y(a){for(;a&&a.length;)a.shift()()}function g(a){this.destroy=l;this.fire("destroy");this.set=this.get=l;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=
this._state=null}function l(){}var u=r("hammerjs");u=u&&u.__esModule?u["default"]:u;a(c.prototype,{destroy:g,get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var c=0;c<a.length;c+=1){var e=a[c];e.__calling||(e.__calling=!0,e.call(this,b),e.__calling=!1)}},observe:function(a,b,c){var e=b.bind(this);c&&!1===c.init||e(this.get()[a],void 0);return this.on(c&&c.defer?"update":"state",function(b){b.changed[a]&&e(b.current[a],
b.previous&&b.previous[a])})},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var c=this._handlers[a]||(this._handlers[a]=[]);c.push(b);return{cancel:function(){var a=c.indexOf(b);~a&&c.splice(a,1)}}},set:function(c){this._set(a({},c));this.root._lock||(this.root._lock=!0,y(this.root._beforecreate),y(this.root._oncreate),y(this.root._aftercreate),this.root._lock=!1)},teardown:g,_set:function(c){var b=this._state,e={},d=!1,f;for(f in c)this._differs(c[f],b[f])&&(e[f]=d=!0);d&&(this._state=
a(a({},b),c),this._recompute(e,this._state),this._bind&&this._bind(e,this._state),this._fragment&&(this.fire("state",{changed:e,current:this._state,previous:b}),this._fragment.p(e,this._state),this.fire("update",{changed:e,current:this._state,previous:b})))},_mount:function(a,b){this._fragment[this._fragment.i?"i":"m"](a,b||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,b){return a!=a?b==b:a!==b||a&&"object"===typeof a||"function"===typeof a}});a(c.prototype,{onAppScroll:function(a){a=
this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var b=a.next();!b.done;b=a.next()){b=$jscomp.makeIterator(b.value);b.next();b=b.next().value;var c=document.getElementById(b.id),e=c.getBoundingClientRect().top;c=c.getBoundingClientRect().bottom;if(0<=e&&c<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});a=document.getElementById("menu-"+b.id);a.classList.add("active");b=a.parentNode;
b.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),b.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));break}}},startMenu:function(a){var b=this;this.set(a);setTimeout(function(){b.scrollToURLMenu()},
10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),b=this.get("menuItemsFlat").filter(function(b){return b.id===a});0<b.length?(b=document.getElementById(b[0].id),b=window.scrollY+b.getBoundingClientRect().top-70,window.scrollTo(0,b)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,
b){b&&b.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,a);this.fire("mobilemenu",{action:"CLOSE"})}});c.prototype._recompute=l;A.exports=c});require.register("components/searchlist.component.svelte",function(p,r,A){function z(){var a=this;this.observe("searchList",function(c){a.fuse=a.setFuse(c)})}function n(a,c){function e(b){a.toggleSearch()}function b(b){a.closeSearch()}function f(b){a.handleSearch(b)}
function g(b){a.isClosable(b)}var l,n,u,p,q,r,y,v,w,x,z,A,E,B=1<c.filteredList.length&&h(a,c),J=1>c.filteredList.length&&m(a,c);return{c:function(){l=document.createElement("div");n=document.createElement("div");u=d("svg");p=d("use");q=document.createTextNode("\n  \n  ");r=document.createElement("div");v=document.createTextNode("\n\n  ");w=document.createElement("div");x=document.createElement("input");z=document.createTextNode("\n    ");B&&B.c();A=document.createTextNode("\n\n    ");J&&J.c();this.h()},
h:function(){p.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-search.svg#icon");p.setAttribute("preserveAspectRatio","xMidYMid");u.addEventListener("click",e,!1);u.setAttribute("class","svg-icon");u.setAttribute("xmlns","http://www.w3.org/2000/svg");u.setAttribute("role","img");u.setAttribute("viewBox","0 0 15 15");n.className="btn btn-svg";r.addEventListener("click",b,!1);r.className=y="SearchListComp--overlay "+(c.isOpen?"active":"");x.addEventListener("input",f,!1);x.addEventListener("keydown",
g,!1);x.setAttribute("type","text");x.className="filter-input";x.placeholder="Search here...";w.className=E="search-popup "+(c.isOpen?"open":"");l.className="SearchListComp"},m:function(b,c){b.insertBefore(l,c);l.appendChild(n);n.appendChild(u);u.appendChild(p);l.appendChild(q);l.appendChild(r);l.appendChild(v);l.appendChild(w);w.appendChild(x);a.refs.input=x;w.appendChild(z);B&&B.m(w,null);w.appendChild(A);J&&J.m(w,null)},p:function(b,c){b.isOpen&&y!==(y="SearchListComp--overlay "+(c.isOpen?"active":
""))&&(r.className=y);1<c.filteredList.length?B?B.p(b,c):(B=h(a,c),B.c(),B.m(w,A)):B&&(B.u(),B.d(),B=null);1>c.filteredList.length?J||(J=m(a,c),J.c(),J.m(w,null)):J&&(J.u(),J.d(),J=null);b.isOpen&&E!==(E="search-popup "+(c.isOpen?"open":""))&&(w.className=E)},u:function(){l.parentNode.removeChild(l);B&&B.u();J&&J.u()},d:function(){u.removeEventListener("click",e,!1);r.removeEventListener("click",b,!1);x.removeEventListener("input",f,!1);x.removeEventListener("keydown",g,!1);a.refs.input===x&&(a.refs.input=
null);B&&B.d();J&&J.d()}}}function w(a,c){var e=c.item,b,d,f,g=e.item.title,l,h,m,n=e.item.content.substr(0,100),u,p,q;return{c:function(){b=document.createElement("li");d=document.createElement("a");f=document.createElement("div");l=document.createTextNode(g);h=document.createTextNode("\n          ");m=document.createElement("div");u=document.createTextNode(n);p=document.createTextNode("...");this.h()},h:function(){f.className="section-title";m.className="section-text";d.addEventListener("click",
x,!1);d.href=q="#/"+e.item.id;d._svelte={component:a};b.className="item"},m:function(a,c){a.insertBefore(b,c);b.appendChild(d);d.appendChild(f);f.appendChild(l);d.appendChild(h);d.appendChild(m);m.appendChild(u);m.appendChild(p)},p:function(a,b){e=b.item;a.filteredList&&g!==(g=e.item.title)&&(l.data=g);a.filteredList&&n!==(n=e.item.content.substr(0,100))&&(u.data=n);a.filteredList&&q!==(q="#/"+e.item.id)&&(d.href=q)},u:function(){b.parentNode.removeChild(b)},d:function(){d.removeEventListener("click",
x,!1)}}}function h(a,d){for(var e,b=d.filteredList,f=[],g=0;g<b.length;g+=1)f[g]=w(a,c(c({},d),{each_value:b,item:b[g],item_index:g}));return{c:function(){e=document.createElement("ul");for(var a=0;a<f.length;a+=1)f[a].c();this.h()},h:function(){e.className="filtered-list"},m:function(a,b){a.insertBefore(e,b);for(a=0;a<f.length;a+=1)f[a].m(e,null)},p:function(b,d){var g=d.filteredList;if(b.filteredList){for(var l=0;l<g.length;l+=1){var k=c(c({},d),{each_value:g,item:g[l],item_index:l});f[l]?f[l].p(b,
k):(f[l]=w(a,k),f[l].c(),f[l].m(e,null))}for(;l<f.length;l+=1)f[l].u(),f[l].d();f.length=g.length}},u:function(){e.parentNode.removeChild(e);for(var a=0;a<f.length;a+=1)f[a].u()},d:function(){for(var a=0;a<f.length;a+=1)f[a]&&f[a].d()}}}function m(c,d){var e;return{c:function(){e=document.createElement("h2");e.textContent="No matches found.";this.h()},h:function(){e.className="empty-message"},m:function(a,c){a.insertBefore(e,c)},u:function(){e.parentNode.removeChild(e)},d:a}}function x(a){this._svelte.component.closeSearch()}
function q(a){v(this,a);this.refs={};this._state=c({searchList:[],filteredList:[],fuse:null,isOpen:!1},a.data);var d=this;a.root||(this._oncreate=[]);this._fragment=n(this,this._state);this.root._oncreate.push(function(){z.call(d);d.fire("update",{changed:{isOpen:1,filteredList:1},current:d._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),f(this._oncreate))}function d(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function c(a,c){for(var e in c)a[e]=c[e];
return a}function a(){}function v(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function f(a){for(;a&&a.length;)a.shift()()}function y(c){this.destroy=a;this.fire("destroy");this.set=this.get=a;!1!==c&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var g=r("fuse.js");g=g&&g.__esModule?g["default"]:g;c(q.prototype,{destroy:y,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&
this._handlers[a].slice())for(var e=0;e<a.length;e+=1){var b=a[e];b.__calling||(b.__calling=!0,b.call(this,c),b.__calling=!1)}},observe:function(a,c,e){var b=c.bind(this);e&&!1===e.init||b(this.get()[a],void 0);return this.on(e&&e.defer?"update":"state",function(c){c.changed[a]&&b(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var e=this._handlers[a]||(this._handlers[a]=[]);e.push(c);return{cancel:function(){var a=e.indexOf(c);~a&&e.splice(a,
1)}}},set:function(a){this._set(c({},a));this.root._lock||(this.root._lock=!0,f(this.root._beforecreate),f(this.root._oncreate),f(this.root._aftercreate),this.root._lock=!1)},teardown:y,_set:function(a){var d=this._state,e={},b=!1,f;for(f in a)this._differs(a[f],d[f])&&(e[f]=b=!0);b&&(this._state=c(c({},d),a),this._recompute(e,this._state),this._bind&&this._bind(e,this._state),this._fragment&&(this.fire("state",{changed:e,current:this._state,previous:d}),this._fragment.p(e,this._state),this.fire("update",
{changed:e,current:this._state,previous:d})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});c(q.prototype,{openSearch:function(){this.set({isOpen:!0});this.refs.input.focus()},closeSearch:function(){this.set({isOpen:!1})},toggleSearch:function(){this.get("isOpen")?this.closeSearch():this.openSearch()},isClosable:function(a){27===
a.keyCode&&this.closeSearch()},setFuse:function(a){1>a.length||this.set({fuse:new g(a,{shouldSort:!0,findAllMatches:!0,includeMatches:!0,threshold:.3,location:0,distance:1E4,maxPatternLength:32,minMatchCharLength:3,keys:["content"]})})},handleSearch:function(a){3<a.target.value.length?this.set({filteredList:this.get("fuse").search(a.target.value)}):this.set({filteredList:[]});console.log(this.get("filteredList"))}});q.prototype._recompute=a;A.exports=q});require.register("components/topbar.component.svelte",
function(p,r,A){function z(c,d){function f(a){c.fire("mobilemenu",{action:"TOGGLE"})}function l(a){c.scrollTop()}var h,e,b,k,p,q,r,y,v,x,z,A,D=d.settings.allow_font_size_control&&n(c,d),E=new a({root:c.root});c.refs.searchlist=E;var B=d.settings.allow_topbar_link&&w(c,d);return{c:function(){h=document.createElement("div");e=document.createElement("div");b=m("svg");k=m("use");q=document.createTextNode("\n\n    ");r=document.createElement("div");r.innerHTML='\x3cimg src\x3d"img/logo.svg" alt\x3d"Docs" width\x3d"182"\x3e';
y=document.createTextNode("\n\n    ");D&&D.c();v=document.createTextNode("\n\n    ");x=document.createElement("hr");z=document.createTextNode("\n\n    ");E._fragment.c();A=document.createTextNode("\n\n    ");B&&B.c();this.h()},h:function(){k.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-menu-open.svg#icon");k.setAttribute("preserveAspectRatio","xMidYMid");var a=p="svg-icon "+(d.isMenuOpen?"off":"");b.setAttribute("class",a);b.setAttribute("xmlns","http://www.w3.org/2000/svg");
b.setAttribute("role","img");b.setAttribute("viewBox","0 0 40 28");e.addEventListener("click",f,!1);e.className="menu-button";r.addEventListener("click",l,!1);r.className="logo";h.className="TopbarComp"},m:function(a,c){a.insertBefore(h,c);h.appendChild(e);e.appendChild(b);b.appendChild(k);h.appendChild(q);h.appendChild(r);h.appendChild(y);D&&D.m(h,null);h.appendChild(v);h.appendChild(x);h.appendChild(z);E._mount(h,null);h.appendChild(A);B&&B.m(h,null)},p:function(a,e){a.isMenuOpen&&p!==(p="svg-icon "+
(e.isMenuOpen?"off":""))&&b.setAttribute("class",p);e.settings.allow_font_size_control?D||(D=n(c,e),D.c(),D.m(h,v)):D&&(D.u(),D.d(),D=null);e.settings.allow_topbar_link?B?B.p(a,e):(B=w(c,e),B.c(),B.m(h,null)):B&&(B.u(),B.d(),B=null)},u:function(){h.parentNode.removeChild(h);D&&D.u();B&&B.u()},d:function(){e.removeEventListener("click",f,!1);r.removeEventListener("click",l,!1);D&&D.d();E.destroy(!1);c.refs.searchlist===E&&(c.refs.searchlist=null);B&&B.d()}}}function n(a,c){function d(b){a.fire("fontsize",
{action:"DECREASE"})}function f(b){a.fire("fontsize",{action:"INCREASE"})}var h,e,b,k;return{c:function(){h=document.createElement("div");e=document.createElement("div");e.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-minus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';b=document.createTextNode("\n      ");k=document.createElement("div");k.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-plus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';
this.h()},h:function(){e.addEventListener("click",d,!1);e.className="btn btn-svg v-center";k.addEventListener("click",f,!1);k.className="btn btn-svg v-center";h.className="btn-group"},m:function(a,c){a.insertBefore(h,c);h.appendChild(e);h.appendChild(b);h.appendChild(k)},u:function(){h.parentNode.removeChild(h)},d:function(){e.removeEventListener("click",d,!1);k.removeEventListener("click",f,!1)}}}function w(a,c){var d,f,h=c.settings.topbar_link_small_label,e,b,k=c.settings.topbar_link_label,m,n;
return{c:function(){d=document.createElement("a");f=document.createElement("span");e=document.createTextNode(h);b=document.createElement("b");m=document.createTextNode(k);this.h()},h:function(){d.href=n=c.settings.topbar_link_url;d.className="btn btn-last-link"},m:function(a,c){a.insertBefore(d,c);d.appendChild(f);f.appendChild(e);d.appendChild(b);b.appendChild(m)},p:function(a,b){a.settings&&h!==(h=b.settings.topbar_link_small_label)&&(e.data=h);a.settings&&k!==(k=b.settings.topbar_link_label)&&
(m.data=k);a.settings&&n!==(n=b.settings.topbar_link_url)&&(d.href=n)},u:function(){d.parentNode.removeChild(d)},d:x}}function h(a){this._handlers=Object.create(null);this._bind=a._bind;this.options=a;this.root=a.root||this;this.store=this.root.store||a.store;this.refs={};this._state=q({settings:v},a.data);a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,d(this._beforecreate),
d(this._oncreate),d(this._aftercreate),this._lock=!1)}function m(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function x(){}function q(a,c){for(var d in c)a[d]=c[d];return a}function d(a){for(;a&&a.length;)a.shift()()}function c(a){this.destroy=x;this.fire("destroy");this.set=this.get=x;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var a=r("./searchlist.component"),v=r("../herodotus-settings.js");a=a&&a.__esModule?a["default"]:a;v=v&&v.__esModule?
v["default"]:v;q(h.prototype,{destroy:c,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var d=0;d<a.length;d+=1){var f=a[d];f.__calling||(f.__calling=!0,f.call(this,c),f.__calling=!1)}},observe:function(a,c,d){var f=c.bind(this);d&&!1===d.init||f(this.get()[a],void 0);return this.on(d&&d.defer?"update":"state",function(c){c.changed[a]&&f(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",
c);var d=this._handlers[a]||(this._handlers[a]=[]);d.push(c);return{cancel:function(){var a=d.indexOf(c);~a&&d.splice(a,1)}}},set:function(a){this._set(q({},a));this.root._lock||(this.root._lock=!0,d(this.root._beforecreate),d(this.root._oncreate),d(this.root._aftercreate),this.root._lock=!1)},teardown:c,_set:function(a){var c=this._state,d={},f=!1,h;for(h in a)this._differs(a[h],c[h])&&(d[h]=f=!0);f&&(this._state=q(q({},c),a),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&
(this.fire("state",{changed:d,current:this._state,previous:c}),this._fragment.p(d,this._state),this.fire("update",{changed:d,current:this._state,previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});h.prototype._recompute=x;A.exports=h});require.register("herodotus-settings.js",function(p,r,A){Object.defineProperty(p,
"__esModule",{value:!0});p.default={documentation_name:"UnoCode Documentation",allow_topbar_link:!0,topbar_link_small_label:"Visit our",topbar_link_label:"Website",topbar_link_url:"http://unocode.com.br/",allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",function(p,r,A){var z=(p=r("./components/main.component"))&&p.__esModule?p:{default:p};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=new z.default({target:document.querySelector("main")})})});
require.alias("@fdaciuk/ajax/dist/ajax.min.js","@fdaciuk/ajax");require.alias("fuse.js/dist/fuse.js","fuse.js");require.alias("hammerjs/hammer.js","hammerjs");require.alias("marked/lib/marked.js","marked");require.alias("prismjs/prism.js","prismjs");require.register("___globals___",function(p,r,A){})})();require("___globals___");require("initialize");